<h1><center>Laboratorio 6: Optimización de modelos 🧪</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>

### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Daniel Vargas
- Nombre de alumno 2: Rafael Tapia


Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

### **Link de repositorio de GitHub:** [Insertar Repositorio](https://github.com/rodusflitope/DataScienceLabs/tree/lab6)

### Temas a tratar

- Predicción de demanda usando `xgboost`
- Búsqueda del modelo óptimo de clasificación usando `optuna`
- Uso de pipelines.


### Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: 6 días de plazo con descuento de 1 punto por día. Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda fuertemente asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

# Importamos librerias útiles

In [54]:
!pip install -qq xgboost optuna

# El emprendimiento de Fiu

Tras liderar de manera exitosa la implementación de un proyecto de ciencia de datos para caracterizar los datos generados en Santiago 2023, el misterioso corpóreo **Fiu** se anima y decide levantar su propio negocio de consultoría en machine learning. Tras varias e intensas negociaciones, Fiu logra encontrar su *primera chamba*: predecir la demanda (cantidad de venta) de una famosa productora de bebidas de calibre mundial. Al ver el gran potencial y talento que usted ha demostrado en el campo de la ciencia de datos, Fiu lo contrata como data scientist para que forme parte de su nuevo emprendimiento.

Para este laboratorio deben trabajar con los datos `sales.csv` subidos a u-cursos, el cual contiene una muestra de ventas de la empresa para diferentes productos en un determinado tiempo.

Para comenzar, cargue el dataset señalado y visualice a través de un `.head` los atributos que posee el dataset.

<i><p align="center">Fiu siendo felicitado por su excelente desempeño en el proyecto de caracterización de datos</p></i>
<p align="center">
  <img src="https://media-front.elmostrador.cl/2023/09/A_UNO_1506411_2440e.jpg">
</p>

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

df = pd.read_csv('sales.csv')

df.head()

id      date    city       lat      long     pop    shop        brand  \
0   0  31/01/12  Athens  37.97945  23.71622  672130  shop_1  kinder-cola   
1   1  31/01/12  Athens  37.97945  23.71622  672130  shop_1  kinder-cola   
2   2  31/01/12  Athens  37.97945  23.71622  672130  shop_1  kinder-cola   
3   3  31/01/12  Athens  37.97945  23.71622  672130  shop_1   adult-cola   
4   4  31/01/12  Athens  37.97945  23.71622  672130  shop_1   adult-cola   

  container capacity  price  quantity  
0     glass    500ml   0.96     13280  
1   plastic    1.5lt   2.86      6727  
2       can    330ml   0.87      9848  
3     glass    500ml   1.00     20050  
4       can    330ml   0.39     25696

## 1 Generando un Baseline (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/O-lan6TkadUAAAAC/what-i-wnna-do-after-a-baseline.gif">
</p>

Antes de entrenar un algoritmo, usted recuerda los apuntes de su magíster en ciencia de datos y recuerda que debe seguir una serie de *buenas prácticas* para entrenar correcta y debidamente su modelo. Después de un par de vueltas, llega a las siguientes tareas:

1. Separe los datos en conjuntos de train (70%), validation (20%) y test (10%). Fije una semilla para controlar la aleatoriedad. [0.5 puntos]
2. Implemente un `FunctionTransformer` para extraer el día, mes y año de la variable `date`. Guarde estas variables en el formato categorical de pandas. [1 punto]
3. Implemente un `ColumnTransformer` para procesar de manera adecuada los datos numéricos y categóricos. Use `OneHotEncoder` para las variables categóricas. `Nota:` Utilice el método `.set_output(transform='pandas')` para obtener un DataFrame como salida del `ColumnTransformer` [1 punto]
4. Guarde los pasos anteriores en un `Pipeline`, dejando como último paso el regresor `DummyRegressor` para generar predicciones en base a promedios. [0.5 punto]
5. Entrene el pipeline anterior y reporte la métrica `mean_absolute_error` sobre los datos de validación. ¿Cómo se interpreta esta métrica para el contexto del negocio? [0.5 puntos]
6. Finalmente, vuelva a entrenar el `Pipeline` pero esta vez usando `XGBRegressor` como modelo **utilizando los parámetros por default**. ¿Cómo cambia el MAE al implementar este algoritmo? ¿Es mejor o peor que el `DummyRegressor`? [1 punto]
7. Guarde ambos modelos en un archivo .pkl (uno cada uno) [0.5 puntos]

In [2]:
from sklearn import set_config
set_config(transform_output="pandas")

from sklearn.model_selection import train_test_split

RANDOM_STATE = 10

train_df, test_df = train_test_split(df, test_size=0.1, random_state=RANDOM_STATE)
train_df, val_df = train_test_split(train_df, test_size=2/9, random_state=RANDOM_STATE)

target_column = 'quantity'

X_train = train_df.drop(target_column, axis=1)
y_train = train_df[target_column]

X_val = val_df.drop(target_column, axis=1)
y_val = val_df[target_column]

X_test = test_df.drop(target_column, axis=1)
y_test = test_df[target_column]

In [3]:
from sklearn.preprocessing import FunctionTransformer

def extract_date_features(X):
    X_copy = X.copy()
    # Convertir la columna 'date' a datetime si no lo está
    X_copy['date'] = pd.to_datetime(X_copy['date'], format='%d/%m/%y')
    # Extraer día, mes y año
    X_copy['day'] = X_copy['date'].dt.day.astype('category')
    X_copy['month'] = X_copy['date'].dt.month.astype('category')
    X_copy['year'] = X_copy['date'].dt.year.astype('category')
    # Eliminamos la fecha original para no OHE-encodearla completa porque da warning
    X_copy = X_copy.drop(columns=['date'])
    return X_copy

date_transformer = FunctionTransformer(
    extract_date_features
)

X_train_dates = date_transformer.fit_transform(X_train)

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numeric_features = X_train_dates.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X_train_dates.select_dtypes(include=['category', 'object']).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),  # Escalar variables numéricas porque no dice que hacer con ellas
        ('cat', OneHotEncoder(sparse_output=False), categorical_features)
    ],
    remainder='passthrough'  # Mantener cualquier columna restante por si se me olvida algun tipo de col
)

preprocessor.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('num', StandardScaler(),
                                 ['id', 'lat', 'long', 'pop', 'price']),
                                ('cat', OneHotEncoder(sparse_output=False),
                                 ['city', 'shop', 'brand', 'container',
                                  'capacity', 'day', 'month', 'year'])])

In [5]:
from sklearn.dummy import DummyRegressor
from sklearn.pipeline import Pipeline

baseline_pipeline = Pipeline([
    ('date_features', date_transformer), 
    ('preprocessor', preprocessor),
    ('regressor', DummyRegressor(strategy='mean'))
])

In [6]:
baseline_pipeline.fit(X_train, y_train)

Pipeline(steps=[('date_features',
                 FunctionTransformer(func=<function extract_date_features at 0x00000199C254A700>)),
                ('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['id', 'lat', 'long', 'pop',
                                                   'price']),
                                                 ('cat',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['city', 'shop', 'brand',
                                                   'container', 'capacity',
                                                   'day', 'month', 'year'])])),
                ('regressor', DummyRegressor())])

In [7]:
from sklearn.metrics import mean_absolute_error

y_val_pred = baseline_pipeline.predict(X_val)
mae_baseline = mean_absolute_error(y_val, y_val_pred)

print(f'MAE del modelo baseline en validacion: {mae_baseline:.2f}')

MAE del modelo baseline en validacion: 13176.15


Un MAE de 13176 significa que en promedio esto es lo que se equivoca mi modelo en relación al valor real, es decir, si predigo un valor k, entonces espero que me equivoque en 13176 unidades con respecto al valor real.

In [8]:
from xgboost import XGBRegressor
import joblib

xgb_pipeline = Pipeline([
    ('date_features', date_transformer),
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(
        random_state=RANDOM_STATE,
    ))
])

xgb_pipeline.fit(X_train, y_train)

y_val_pred_xgb = xgb_pipeline.predict(X_val)
mae_xgb = mean_absolute_error(y_val, y_val_pred_xgb)

print(f"MAE XGBRegressor validacion: {mae_xgb:.2f}")

joblib.dump(baseline_pipeline, "baseline_dummy.pkl")
joblib.dump(xgb_pipeline, "xgb_default.pkl")

MAE XGBRegressor validacion: 2545.91


['xgb_default.pkl']

Bajo muchisimo el MAE a 2546, esto significa que el modelo en promedio se acerca mucho más al valor real pues epero equivocarme eso al hacer una predicción de la cantidad de compra de algo.

## 2. Forzando relaciones entre parámetros con XGBoost (10 puntos)

<p align="center">
  <img src="https://64.media.tumblr.com/14cc45f9610a6ee341a45fd0d68f4dde/20d11b36022bca7b-bf/s640x960/67ab1db12ff73a530f649ac455c000945d99c0d6.gif">
</p>

Un colega aficionado a la economía le *sopla* que la demanda guarda una relación inversa con el precio del producto. Motivado para impresionar al querido corpóreo, se propone hacer uso de esta información para mejorar su modelo realizando las siguientes tareas:

1. Vuelva a entrenar el `Pipeline` con `XGBRegressor`, pero esta vez forzando una relación monótona negativa entre el precio y la cantidad. Para aplicar esta restricción apóyese en la siguiente <a href = https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html>documentación</a>. [6 puntos]

>Hint 1: Para implementar el constraint se le sugiere hacerlo especificando el nombre de la variable. De ser así, probablemente le sea útil **mantener el formato de pandas** antes del step de entrenamiento.

>Hint 2: Puede obtener el nombre de las columnas en el paso anterior al modelo regresor mediante el método `.get_feature_names_out()`

2. Luego, vuelva a reportar el `MAE` sobre el conjunto de validación. [1 puntos]

3. ¿Cómo cambia el error al incluir esta relación? ¿Tenía razón su amigo? [2 puntos]

4. Guarde su modelo en un archivo .pkl [1 punto]

In [9]:
xgb_monotone_pipeline = Pipeline([
    ('date_features', date_transformer),
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(
        monotone_constraints={'num__price': -1}, 
        random_state=RANDOM_STATE,
    ))
])

xgb_monotone_pipeline.fit(X_train, y_train)
mae_xgb_mon = mean_absolute_error(y_val, xgb_monotone_pipeline.predict(X_val))

print(f"MAE XGB default:      {mae_xgb:.2f}")
print(f"MAE XGB monotónico:   {mae_xgb_mon:.2f}")

joblib.dump(xgb_monotone_pipeline, "xgb_monotone_price_neg.pkl")

MAE XGB default:      2545.91
MAE XGB monotónico:   2510.53


['xgb_monotone_price_neg.pkl']

Tenia razón pues mejoro ligeramente la calidad de la predicción (según MAE)

## 1.3 Optimización de Hiperparámetros con Optuna (20 puntos)

<p align="center">
  <img src="https://media.tenor.com/fmNdyGN4z5kAAAAi/hacking-lucy.gif">
</p>

Luego de presentarle sus resultados, Fiu le pregunta si es posible mejorar *aun más* su modelo. En particular, le comenta de la optimización de hiperparámetros con metodologías bayesianas a través del paquete `optuna`. Como usted es un aficionado al entrenamiento de modelos de ML, se propone implementar la descabellada idea de su jefe.

A partir de la mejor configuración obtenida en la sección anterior, utilice `optuna` para optimizar sus hiperparámetros. En particular, se pide que su optimización considere lo siguiente:

- Fijar una semilla en las instancias necesarias para garantizar la reproducibilidad de resultados
- Utilice `TPESampler` como método de muestreo
- De `XGBRegressor`, optimice los siguientes hiperparámetros:
    - `learning_rate` buscando valores flotantes en el rango (0.001, 0.1)
    - `n_estimators` buscando valores enteros en el rango (50, 1000)
    - `max_depth` buscando valores enteros en el rango (3, 10)
    - `max_leaves` buscando valores enteros en el rango (0, 100)
    - `min_child_weight` buscando valores enteros en el rango (1, 5)
    - `reg_alpha` buscando valores flotantes en el rango (0, 1)
    - `reg_lambda` buscando valores flotantes en el rango (0, 1)
- De `OneHotEncoder`, optimice el hiperparámetro `min_frequency` buscando el mejor valor flotante en el rango (0.0, 1.0)

Para ello se pide los siguientes pasos:
1. Implemente una función `objective()` que permita minimizar el `MAE` en el conjunto de validación. Use el método `.set_user_attr()` para almacenar el mejor pipeline entrenado. [10 puntos]
2. Fije el tiempo de entrenamiento a 5 minutos. [1 punto]
3. Optimizar el modelo y reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
4. Explique cada hiperparámetro y su rol en el modelo. ¿Hacen sentido los rangos de optimización indicados? [5 puntos]
5. Guardar su modelo en un archivo .pkl [1 punto]

In [22]:
import optuna
from optuna.samplers import TPESampler
from sklearn.base import clone
optuna.logging.set_verbosity(optuna.logging.WARNING)
# Inserte su código acá

#Esto es para que al construir el preprocesador en cada trial se pruebe con el min_frequency escogido
def build_preprocessor(min_freq):
    prep = clone(preprocessor)
    prep.set_params(cat__min_frequency=min_freq)
    return prep

def objective(trial):
    # Hiperparámetros a optimizar (rangos del enunciado)
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1, log=True)
    n_estimators = trial.suggest_int("n_estimators", 50, 1000)
    max_depth = trial.suggest_int("max_depth", 3, 10)
    max_leaves = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha = trial.suggest_float("reg_alpha", 0.0, 1.0)
    reg_lambda = trial.suggest_float("reg_lambda", 0.0, 1.0)
    ohe_min_freq = trial.suggest_float("ohe_min_frequency", 0.0, 1.0)

    # Preprocessor con min_frequency escogido
    prep = build_preprocessor(ohe_min_freq)

    # Modelo XGB
    xgb = XGBRegressor(
        random_state=RANDOM_STATE,
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        max_leaves=max_leaves,
        min_child_weight=min_child_weight,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        monotone_constraints={'num__price': -1}
    )

    pipe = Pipeline([
        ('date_features', date_transformer),
        ('preprocessor', prep), # Uso el que tiene el hiperparametro, no el que esta fijo
        ('regressor', xgb)
    ])

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_val)
    mae = mean_absolute_error(y_val, y_pred)

    # Guardar pipeline y mae en los atributos del trial
    trial.set_user_attr("pipeline", pipe)
    trial.set_user_attr("mae", mae)

    return mae

study = optuna.create_study(direction="minimize", sampler=TPESampler(seed=RANDOM_STATE))
study.optimize(objective, timeout=300, show_progress_bar=True)

best_trial = study.best_trial
best_mae = best_trial.value
best_pipeline = best_trial.user_attrs["pipeline"]

print(f"Trials ejecutados: {len(study.trials)}")
print(f"Mejor MAE validación: {best_mae:.2f}")
print("Mejores hiperparámetros:")
for k,v in best_trial.params.items():
    print(f"  {k}: {v}")

joblib.dump(best_pipeline, "xgb_optuna.pkl")

Best trial: 93. Best value: 2008.55:  100%|██████████| 05:02/05:00


Trials ejecutados: 136
Mejor MAE validación: 2008.55
Mejores hiperparámetros:
  learning_rate: 0.03587694736422289
  n_estimators: 915
  max_depth: 9
  max_leaves: 100
  min_child_weight: 4
  reg_alpha: 0.8371112697125426
  reg_lambda: 0.04751105932555697
  ohe_min_frequency: 0.019020612698596513


['xgb_optuna.pkl']

Los resultados mejoraron 
pues lo que se hace es probar combinaciones de hiperparámetros e ir guardando la combinación que tenga la mejor métrica (en este caso menor MAE). Por esto, si en los valores propuestos estan los que usamos como baseline, el resultado necesariamente es igual o mejor porque en peor caso se usan lo que ya se usaron.

**learning_rate**: tamaño del paso de optimización se usa normalmente entre ese rango.

**n_estimators**: número de árboles boosting, tiene sentido el tamaño pues más de 1000 puede ser muy costoso.

**max_depth**: profundidad máxima, es para evitar overfitting en los árboles, quizas podría aumentar pero depende de la cantidad de parámetros y tenemos pocos.

**max_leaves**: límite de hojas, también depende de la cantidad de valores posibles y parámetros.

**min_child_weight**: mínimo peso para hacer un split, tiene sentido el árbol pues es laxo y como es un mínimo dificilmente nos dejara fuera un buen valor. Podría aumentarse el rango.

**reg_alpha**: regularización L1 induce sparsity en pesos de hojas castigando, el rango tiene sentido pues es la ponderación que tiene esta reg y podría ser mayor a 1 pero sería muy exagerado.

**reg_lambda**: regularización L2 reduce magnitud de pesos, estabiliza, por lo mismo que la L1 el rango tiene sentido.

**ohe_min_frequency**: filtra categorías raras agrupándolas reduciendo dimensionalidad, tiene sentido el valor porque como es relativo, estoy abarcando todos los casos, desde no tener mínimo que es 0 a que todo sea el mismo que es 1.

## 4. Optimización de Hiperparámetros con Optuna y Prunners (17 puntos)

<p align="center">
  <img src="https://i.pinimg.com/originals/90/16/f9/9016f919c2259f3d0e8fe465049638a7.gif">
</p>

Después de optimizar el rendimiento de su modelo varias veces, Fiu le pregunta si no es posible optimizar el entrenamiento del modelo en sí mismo. Después de leer un par de post de personas de dudosa reputación en la *deepweb*, usted llega a la conclusión que puede cumplir este objetivo mediante la implementación de **Prunning**.

Vuelva a optimizar los mismos hiperparámetros que la sección pasada, pero esta vez utilizando **Prunning** en la optimización. En particular, usted debe:

- Responder: ¿Qué es prunning? ¿De qué forma debería impactar en el entrenamiento? [2 puntos]
- Redefinir la función `objective()` utilizando `optuna.integration.XGBoostPruningCallback` como método de **Prunning** [10 puntos]
- Fijar nuevamente el tiempo de entrenamiento a 5 minutos [1 punto]
- Reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
- Guardar su modelo en un archivo .pkl [1 punto]

Nota: Si quieren silenciar los prints obtenidos en el prunning, pueden hacerlo mediante el siguiente comando:

```
optuna.logging.set_verbosity(optuna.logging.WARNING)
```

De implementar la opción anterior, pueden especificar `show_progress_bar = True` en el método `optimize` para *más sabor*.

Hint: Si quieren especificar parámetros del método .fit() del modelo a través del pipeline, pueden hacerlo por medio de la siguiente sintaxis: `pipeline.fit(stepmodelo__parametro = valor)`

Hint2: Este <a href = https://stackoverflow.com/questions/40329576/sklearn-pass-fit-parameters-to-xgboost-in-pipeline>enlace</a> les puede ser de ayuda en su implementación

In [76]:
!pip install optuna-integration[xgboost]

   ---------------------------------------- 0.0/99.1 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/99.1 kB ? eta -:--:--
   ------------------------------------- -- 92.2/99.1 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 99.1/99.1 kB 1.1 MB/s eta 0:00:00


Existen 2 formas de prunning, el pre-prunning y el post-prunning, le pre-prunning es lo que ya hicimos que es podar el árbol de forma preventiva poniendole límites como max-depth, max-leaves, etc.

El post prunning es una vez ya construido el árbol se evalua que puedo eliminar sin afectar mucho el rendimiento del árbol y las elimino, esto aunque muchas veces empeora el rendimiento del árbol en el conjunto de entrenamieno y validación, evita overfitting y debería después el árbol ser menos complejo y generalizar mejor.

En nuestro caso nuestro prunning lo que hace es hacer el pre-prunning de detener pero a la misma optimización de hiperparámetros por lo que el modelo debe generalizar mejor después aunque empeore un poco según validación.

In [20]:
# Inserte su código acá
from optuna.integration import XGBoostPruningCallback

optuna.logging.set_verbosity(optuna.logging.WARNING)

def build_preprocessor(min_freq):
    prep = clone(preprocessor)
    prep.set_params(cat__min_frequency=min_freq)
    return prep

def objective_pruning(trial):
    # Hiperparámetros
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1, log=True)
    n_estimators = trial.suggest_int("n_estimators", 50, 1000)
    max_depth = trial.suggest_int("max_depth", 3, 10)
    max_leaves = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha = trial.suggest_float("reg_alpha", 0.0, 1.0)
    reg_lambda = trial.suggest_float("reg_lambda", 0.0, 1.0)
    ohe_min_freq = trial.suggest_float("ohe_min_frequency", 0.0, 1.0)

    prep = build_preprocessor(ohe_min_freq)


    featurizer = Pipeline([
        ('date_features', date_transformer),
        ('preprocessor',  prep)
    ])
    featurizer.fit(X_train, y_train)

    X_val_fe = featurizer.transform(X_val)

    pruning_cb = XGBoostPruningCallback(trial, "validation_0-mae")

    xgb = XGBRegressor(
        random_state=RANDOM_STATE,
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        max_leaves=max_leaves,
        min_child_weight=min_child_weight,
        reg_alpha=reg_alpha,
        reg_lambda=reg_lambda,
        monotone_constraints={'num__price': -1},
        eval_metric="mae",
        callbacks=[pruning_cb]
    )

    pipe = Pipeline([
        ('date_features', date_transformer),
        ('preprocessor', prep),
        ('regressor', xgb)
    ])

    # Entrena con eval_set para que Optuna reciba métricas por iteración
    pipe.fit(
        X_train,
        y_train,
        regressor__eval_set=[(X_val_fe, y_val)],
        )

    pred = pipe.predict(X_val)
    mae = mean_absolute_error(y_val, pred)

    trial.set_user_attr("pipeline", pipe)
    trial.set_user_attr("mae", mae)
    return mae

study_prune = optuna.create_study(direction="minimize", sampler=TPESampler(seed=RANDOM_STATE))
study_prune.optimize(objective_pruning, timeout=300, show_progress_bar=True)

best_trial_p = study_prune.best_trial
best_mae_p = best_trial_p.value
best_pipeline_p = best_trial_p.user_attrs["pipeline"]

print(f"Trials ejecutados: {len(study_prune.trials)}")
print(f"Mejor MAE validación: {best_mae_p:.2f}")
print("Mejores hiperparámetros:")
for k,v in best_trial_p.params.items():
    print(f"  {k}: {v}")

joblib.dump(best_pipeline_p, "xgb_optuna_pruning.pkl")

   0%|          | 00:00/05:00

[0]	validation_0-mae:12936.86798
[1]	validation_0-mae:12698.28403
[2]	validation_0-mae:12472.10525
[3]	validation_0-mae:12256.06570
[4]	validation_0-mae:12052.66956
[5]	validation_0-mae:11858.01188
[6]	validation_0-mae:11677.08460
[7]	validation_0-mae:11508.20789
[8]	validation_0-mae:11350.23560
[9]	validation_0-mae:11195.80685
[10]	validation_0-mae:11053.46771
[11]	validation_0-mae:10920.13034
[12]	validation_0-mae:10791.18215
[13]	validation_0-mae:10670.71907
[14]	validation_0-mae:10558.44026
[15]	validation_0-mae:10453.95557
[16]	validation_0-mae:10350.27999
[17]	validation_0-mae:10254.37531
[18]	validation_0-mae:10163.36666
[19]	validation_0-mae:10077.88336
[20]	validation_0-mae:9996.95586
[21]	validation_0-mae:9918.49066
[22]	validation_0-mae:9842.67945
[23]	validation_0-mae:9773.82985
[24]	validation_0-mae:9705.30802
[25]	validation_0-mae:9639.73675
[26]	validation_0-mae:9578.89902
[27]	validation_0-mae:9521.08228
[28]	validation_0-mae:9466.66860
[29]	validation_0-mae:9418.12813


Best trial: 0. Best value: 8298.11:    0%|          | 00:00/05:00

[0]	validation_0-mae:13161.00559
[1]	validation_0-mae:13145.86464
[2]	validation_0-mae:13130.84355
[3]	validation_0-mae:13115.84825
[4]	validation_0-mae:13100.88652
[5]	validation_0-mae:13086.02844
[6]	validation_0-mae:13070.47899
[7]	validation_0-mae:13054.96307
[8]	validation_0-mae:13039.50897
[9]	validation_0-mae:13024.10713
[10]	validation_0-mae:13008.80108
[11]	validation_0-mae:12993.56139
[12]	validation_0-mae:12978.31344
[13]	validation_0-mae:12963.17276
[14]	validation_0-mae:12948.05089
[15]	validation_0-mae:12932.93237
[16]	validation_0-mae:12918.01537
[17]	validation_0-mae:12903.04652
[18]	validation_0-mae:12888.28525
[19]	validation_0-mae:12873.36785
[20]	validation_0-mae:12858.69928
[21]	validation_0-mae:12843.94732
[22]	validation_0-mae:12829.36604
[23]	validation_0-mae:12814.78141
[24]	validation_0-mae:12800.25486
[25]	validation_0-mae:12785.80293
[26]	validation_0-mae:12771.34748
[27]	validation_0-mae:12757.03837
[28]	validation_0-mae:12742.65899
[29]	validation_0-mae:12

Best trial: 0. Best value: 8298.11:    1%|          | 00:01/05:00

[0]	validation_0-mae:12984.33772
[1]	validation_0-mae:12790.54833
[2]	validation_0-mae:12607.68687
[3]	validation_0-mae:12428.14145
[4]	validation_0-mae:12259.39540
[5]	validation_0-mae:12095.93311
[6]	validation_0-mae:11940.00458
[7]	validation_0-mae:11792.76020
[8]	validation_0-mae:11654.73742
[9]	validation_0-mae:11521.20645
[10]	validation_0-mae:11392.66274
[11]	validation_0-mae:11265.37498
[12]	validation_0-mae:11149.53107
[13]	validation_0-mae:11035.50657
[14]	validation_0-mae:10927.73322
[15]	validation_0-mae:10827.33210
[16]	validation_0-mae:10726.58975
[17]	validation_0-mae:10631.01895
[18]	validation_0-mae:10540.74139
[19]	validation_0-mae:10457.88702
[20]	validation_0-mae:10374.04504
[21]	validation_0-mae:10296.01284
[22]	validation_0-mae:10221.03954
[23]	validation_0-mae:10150.76178
[24]	validation_0-mae:10083.54999
[25]	validation_0-mae:10017.72244
[26]	validation_0-mae:9955.68186
[27]	validation_0-mae:9897.14233
[28]	validation_0-mae:9839.36272
[29]	validation_0-mae:9781.

Best trial: 2. Best value: 6834.46:    1%|          | 00:03/05:00

[0]	validation_0-mae:13122.60403
[1]	validation_0-mae:13069.80903
[2]	validation_0-mae:13015.53464
[3]	validation_0-mae:12962.21851
[4]	validation_0-mae:12909.31321
[5]	validation_0-mae:12857.47752
[6]	validation_0-mae:12806.00862
[7]	validation_0-mae:12755.35251
[8]	validation_0-mae:12705.14427
[9]	validation_0-mae:12655.45842
[10]	validation_0-mae:12606.41436
[11]	validation_0-mae:12557.48455
[12]	validation_0-mae:12509.19384
[13]	validation_0-mae:12461.84835
[14]	validation_0-mae:12414.52527
[15]	validation_0-mae:12368.39074
[16]	validation_0-mae:12322.71227
[17]	validation_0-mae:12277.74150
[18]	validation_0-mae:12232.97376
[19]	validation_0-mae:12189.89022
[20]	validation_0-mae:12146.43192
[21]	validation_0-mae:12104.34463
[22]	validation_0-mae:12062.37878
[23]	validation_0-mae:12020.64075
[24]	validation_0-mae:11979.47585
[25]	validation_0-mae:11938.86465
[26]	validation_0-mae:11899.22875
[27]	validation_0-mae:11859.30089
[28]	validation_0-mae:11820.72361
[29]	validation_0-mae:11

Best trial: 2. Best value: 6834.46:    2%|▏         | 00:06/05:00

[0]	validation_0-mae:12798.22060
[1]	validation_0-mae:12436.04913
[2]	validation_0-mae:12106.21522
[3]	validation_0-mae:11832.73200
[4]	validation_0-mae:11572.84774
[5]	validation_0-mae:11341.20962
[6]	validation_0-mae:11130.51390
[7]	validation_0-mae:10942.33778
[8]	validation_0-mae:10768.20658
[9]	validation_0-mae:10604.74739
[10]	validation_0-mae:10466.03062
[11]	validation_0-mae:10335.47950
[12]	validation_0-mae:10216.71554
[13]	validation_0-mae:10101.63038
[14]	validation_0-mae:9994.01252
[15]	validation_0-mae:9907.83352
[16]	validation_0-mae:9815.91341
[17]	validation_0-mae:9731.40410
[18]	validation_0-mae:9661.25397
[19]	validation_0-mae:9596.65142
[20]	validation_0-mae:9539.90568
[21]	validation_0-mae:9487.17582
[22]	validation_0-mae:9428.09403
[23]	validation_0-mae:9387.62579
[24]	validation_0-mae:9339.93240
[25]	validation_0-mae:9309.53836
[26]	validation_0-mae:9264.79709
[27]	validation_0-mae:9216.01796
[28]	validation_0-mae:9184.34291
[29]	validation_0-mae:9157.00821
[30]	v

Best trial: 4. Best value: 6741.27:    3%|▎         | 00:08/05:00

[0]	validation_0-mae:13095.71550


Best trial: 4. Best value: 6741.27:    3%|▎         | 00:08/05:00

[0]	validation_0-mae:13149.73783


Best trial: 4. Best value: 6741.27:    3%|▎         | 00:08/05:00

[0]	validation_0-mae:12561.98340
[1]	validation_0-mae:12015.05634
[2]	validation_0-mae:11552.05656
[3]	validation_0-mae:11151.35822
[4]	validation_0-mae:10812.02953
[5]	validation_0-mae:10533.53024
[6]	validation_0-mae:10287.13175
[7]	validation_0-mae:10081.24705
[8]	validation_0-mae:9891.96191
[9]	validation_0-mae:9730.34137
[10]	validation_0-mae:9596.67436
[11]	validation_0-mae:9446.89332
[12]	validation_0-mae:9348.66694
[13]	validation_0-mae:9243.62983
[14]	validation_0-mae:9167.52618
[15]	validation_0-mae:9098.16717
[16]	validation_0-mae:9040.58727
[17]	validation_0-mae:8982.99623
[18]	validation_0-mae:8928.98801
[19]	validation_0-mae:8886.09866
[20]	validation_0-mae:8831.37600
[21]	validation_0-mae:8774.23151
[22]	validation_0-mae:8702.06167
[23]	validation_0-mae:8650.83286
[24]	validation_0-mae:8591.21456
[25]	validation_0-mae:8549.12111
[26]	validation_0-mae:8492.76728
[27]	validation_0-mae:8453.24658
[28]	validation_0-mae:8423.30096
[29]	validation_0-mae:8383.59465
[30]	validat

Best trial: 4. Best value: 6741.27:    4%|▍         | 00:11/05:00

[0]	validation_0-mae:13169.07513


Best trial: 4. Best value: 6741.27:    4%|▍         | 00:12/05:00

[0]	validation_0-mae:12708.98951
[1]	validation_0-mae:12277.42093
[2]	validation_0-mae:11908.19069
[3]	validation_0-mae:11580.54009
[4]	validation_0-mae:11307.89435
[5]	validation_0-mae:11014.49216
[6]	validation_0-mae:10791.85662
[7]	validation_0-mae:10539.40529
[8]	validation_0-mae:10331.61098
[9]	validation_0-mae:10128.86782
[10]	validation_0-mae:9861.07853
[11]	validation_0-mae:9673.81730
[12]	validation_0-mae:9500.72401
[13]	validation_0-mae:9275.53257
[14]	validation_0-mae:9131.76669
[15]	validation_0-mae:8976.92720
[16]	validation_0-mae:8807.08021
[17]	validation_0-mae:8686.15121
[18]	validation_0-mae:8552.95212
[19]	validation_0-mae:8426.68058
[20]	validation_0-mae:8325.22360
[21]	validation_0-mae:8190.87037
[22]	validation_0-mae:8096.82753
[23]	validation_0-mae:8006.22208
[24]	validation_0-mae:7920.08371
[25]	validation_0-mae:7796.21826
[26]	validation_0-mae:7705.06480
[27]	validation_0-mae:7619.64582
[28]	validation_0-mae:7555.74029
[29]	validation_0-mae:7461.80594
[30]	valid

Best trial: 10. Best value: 3262.19:    6%|▌         | 00:18/05:00

[0]	validation_0-mae:12612.73384
[1]	validation_0-mae:12113.21852
[2]	validation_0-mae:11693.69128
[3]	validation_0-mae:11334.12718
[4]	validation_0-mae:11041.85088
[5]	validation_0-mae:10704.86221
[6]	validation_0-mae:10435.01436
[7]	validation_0-mae:10179.24563
[8]	validation_0-mae:9927.95815
[9]	validation_0-mae:9735.10233
[10]	validation_0-mae:9451.71210
[11]	validation_0-mae:9267.77126
[12]	validation_0-mae:9030.81479
[13]	validation_0-mae:8858.08934
[14]	validation_0-mae:8685.57273
[15]	validation_0-mae:8532.75418
[16]	validation_0-mae:8396.46375
[17]	validation_0-mae:8258.39838
[18]	validation_0-mae:8130.92838
[19]	validation_0-mae:8009.79719
[20]	validation_0-mae:7902.72645
[21]	validation_0-mae:7782.56879
[22]	validation_0-mae:7700.96869
[23]	validation_0-mae:7599.02583
[24]	validation_0-mae:7514.43846
[25]	validation_0-mae:7438.33830
[26]	validation_0-mae:7371.40004
[27]	validation_0-mae:7279.18993
[28]	validation_0-mae:7208.07029
[29]	validation_0-mae:7157.01220
[30]	validat

Best trial: 11. Best value: 3191.76:    8%|▊         | 00:25/05:00

[0]	validation_0-mae:12577.96756
[1]	validation_0-mae:12013.02987
[2]	validation_0-mae:11546.13371
[3]	validation_0-mae:11128.13101
[4]	validation_0-mae:10790.47068
[5]	validation_0-mae:10431.70783
[6]	validation_0-mae:10155.60344
[7]	validation_0-mae:9884.45215
[8]	validation_0-mae:9661.59776
[9]	validation_0-mae:9451.35582
[10]	validation_0-mae:9230.14092
[11]	validation_0-mae:9047.15608
[12]	validation_0-mae:8880.84789
[13]	validation_0-mae:8713.29559
[14]	validation_0-mae:8547.56635
[15]	validation_0-mae:8417.39593
[16]	validation_0-mae:8295.06648
[17]	validation_0-mae:8170.73047
[18]	validation_0-mae:8038.79004
[19]	validation_0-mae:7946.04341
[20]	validation_0-mae:7829.51796
[21]	validation_0-mae:7735.68188
[22]	validation_0-mae:7645.24487
[23]	validation_0-mae:7576.17817
[24]	validation_0-mae:7526.18313
[25]	validation_0-mae:7447.58721
[26]	validation_0-mae:7396.35441
[27]	validation_0-mae:7328.47845
[28]	validation_0-mae:7256.60614
[29]	validation_0-mae:7207.40644
[30]	validati

Best trial: 11. Best value: 3191.76:    9%|▉         | 00:28/05:00

[0]	validation_0-mae:12805.39711
[1]	validation_0-mae:12448.70733
[2]	validation_0-mae:12122.16933
[3]	validation_0-mae:11814.36663
[4]	validation_0-mae:11526.51028
[5]	validation_0-mae:11272.58934
[6]	validation_0-mae:11046.92144
[7]	validation_0-mae:10807.23229
[8]	validation_0-mae:10593.12637
[9]	validation_0-mae:10390.88572
[10]	validation_0-mae:10208.37954
[11]	validation_0-mae:10047.79563
[12]	validation_0-mae:9879.52133
[13]	validation_0-mae:9736.31138
[14]	validation_0-mae:9585.73369
[15]	validation_0-mae:9443.26266
[16]	validation_0-mae:9306.21066
[17]	validation_0-mae:9179.25110
[18]	validation_0-mae:9054.50548
[19]	validation_0-mae:8937.66476
[20]	validation_0-mae:8815.87674
[21]	validation_0-mae:8718.71095
[22]	validation_0-mae:8619.84395
[23]	validation_0-mae:8523.37657
[24]	validation_0-mae:8441.68375
[25]	validation_0-mae:8350.64880
[26]	validation_0-mae:8248.42613
[27]	validation_0-mae:8163.50027
[28]	validation_0-mae:8079.73420
[29]	validation_0-mae:8013.87402
[30]	val

Best trial: 11. Best value: 3191.76:   10%|█         | 00:31/05:00

[0]	validation_0-mae:12825.59053
[1]	validation_0-mae:12481.28309
[2]	validation_0-mae:12163.38486
[3]	validation_0-mae:11873.03518
[4]	validation_0-mae:11619.17235
[5]	validation_0-mae:11353.67530
[6]	validation_0-mae:11126.15204
[7]	validation_0-mae:10909.75041
[8]	validation_0-mae:10718.08268
[9]	validation_0-mae:10526.14815
[10]	validation_0-mae:10348.55828
[11]	validation_0-mae:10174.45419
[12]	validation_0-mae:10029.83614
[13]	validation_0-mae:9874.52529
[14]	validation_0-mae:9727.04377
[15]	validation_0-mae:9586.74083
[16]	validation_0-mae:9462.02729
[17]	validation_0-mae:9344.42871
[18]	validation_0-mae:9218.85223
[19]	validation_0-mae:9105.12743
[20]	validation_0-mae:9007.12676
[21]	validation_0-mae:8912.07250
[22]	validation_0-mae:8808.96355
[23]	validation_0-mae:8724.63920
[24]	validation_0-mae:8640.66954
[25]	validation_0-mae:8546.49235
[26]	validation_0-mae:8454.83745
[27]	validation_0-mae:8371.88142
[28]	validation_0-mae:8302.18432
[29]	validation_0-mae:8224.83740
[30]	va

Best trial: 11. Best value: 3191.76:   12%|█▏        | 00:35/05:00

[0]	validation_0-mae:13124.55670


Best trial: 11. Best value: 3191.76:   12%|█▏        | 00:36/05:00

[0]	validation_0-mae:12494.84446
[1]	validation_0-mae:11875.91947
[2]	validation_0-mae:11323.76790
[3]	validation_0-mae:10856.63253
[4]	validation_0-mae:10446.70594
[5]	validation_0-mae:10095.05154
[6]	validation_0-mae:9780.22642
[7]	validation_0-mae:9495.53033
[8]	validation_0-mae:9262.30092
[9]	validation_0-mae:9022.78805
[10]	validation_0-mae:8816.38664
[11]	validation_0-mae:8623.37402
[12]	validation_0-mae:8469.24225
[13]	validation_0-mae:8280.78135
[14]	validation_0-mae:8105.32059
[15]	validation_0-mae:7942.85012
[16]	validation_0-mae:7798.56929
[17]	validation_0-mae:7663.22186
[18]	validation_0-mae:7559.64577
[19]	validation_0-mae:7455.37830
[20]	validation_0-mae:7369.96209
[21]	validation_0-mae:7274.41637
[22]	validation_0-mae:7207.97599
[23]	validation_0-mae:7139.43558
[24]	validation_0-mae:7064.13662
[25]	validation_0-mae:6993.60643
[26]	validation_0-mae:6922.32432
[27]	validation_0-mae:6862.54449
[28]	validation_0-mae:6783.72677
[29]	validation_0-mae:6735.63655
[30]	validatio

Best trial: 11. Best value: 3191.76:   13%|█▎        | 00:39/05:00

[0]	validation_0-mae:12841.10530
[1]	validation_0-mae:12516.55308
[2]	validation_0-mae:12216.15981
[3]	validation_0-mae:11963.66226
[4]	validation_0-mae:11718.81743
[5]	validation_0-mae:11503.28941
[6]	validation_0-mae:11307.25527
[7]	validation_0-mae:11120.20932
[8]	validation_0-mae:10960.68775
[9]	validation_0-mae:10799.44781
[10]	validation_0-mae:10658.18795
[11]	validation_0-mae:10523.57297
[12]	validation_0-mae:10408.45451
[13]	validation_0-mae:10296.37622
[14]	validation_0-mae:10193.80406
[15]	validation_0-mae:10091.17131
[16]	validation_0-mae:10004.41968
[17]	validation_0-mae:9917.04398
[18]	validation_0-mae:9846.25645
[19]	validation_0-mae:9764.45220
[20]	validation_0-mae:9700.62664
[21]	validation_0-mae:9635.31294
[22]	validation_0-mae:9585.95053
[23]	validation_0-mae:9533.39229
[24]	validation_0-mae:9475.79310
[25]	validation_0-mae:9424.36340
[26]	validation_0-mae:9386.36488
[27]	validation_0-mae:9343.43273
[28]	validation_0-mae:9318.00079
[29]	validation_0-mae:9278.90089
[30

Best trial: 11. Best value: 3191.76:   13%|█▎        | 00:40/05:00

[0]	validation_0-mae:12834.54511
[1]	validation_0-mae:12504.17712
[2]	validation_0-mae:12199.13169
[3]	validation_0-mae:11943.40219
[4]	validation_0-mae:11695.22696
[5]	validation_0-mae:11477.45702
[6]	validation_0-mae:11279.21243
[7]	validation_0-mae:11091.29849
[8]	validation_0-mae:10931.06505
[9]	validation_0-mae:10768.95712
[10]	validation_0-mae:10627.09259
[11]	validation_0-mae:10493.76523
[12]	validation_0-mae:10378.59740
[13]	validation_0-mae:10273.78604
[14]	validation_0-mae:10164.94075
[15]	validation_0-mae:10064.62546
[16]	validation_0-mae:9975.15488
[17]	validation_0-mae:9890.72536
[18]	validation_0-mae:9814.75685
[19]	validation_0-mae:9741.88309
[20]	validation_0-mae:9682.85455
[21]	validation_0-mae:9616.20632
[22]	validation_0-mae:9561.90411
[23]	validation_0-mae:9506.86517
[24]	validation_0-mae:9463.48154
[25]	validation_0-mae:9418.71570
[26]	validation_0-mae:9383.48945
[27]	validation_0-mae:9336.40149
[28]	validation_0-mae:9301.54679
[29]	validation_0-mae:9265.05119
[30]

Best trial: 11. Best value: 3191.76:   14%|█▎        | 00:41/05:00

[0]	validation_0-mae:12723.08556
[1]	validation_0-mae:12327.93444
[2]	validation_0-mae:11951.42942
[3]	validation_0-mae:11617.09721
[4]	validation_0-mae:11333.77784
[5]	validation_0-mae:11034.66034
[6]	validation_0-mae:10804.48226
[7]	validation_0-mae:10566.49398
[8]	validation_0-mae:10352.35236
[9]	validation_0-mae:10144.40217
[10]	validation_0-mae:9953.15636
[11]	validation_0-mae:9759.61603
[12]	validation_0-mae:9593.25314
[13]	validation_0-mae:9420.85859
[14]	validation_0-mae:9236.68738
[15]	validation_0-mae:9068.94995
[16]	validation_0-mae:8864.43725
[17]	validation_0-mae:8669.88234
[18]	validation_0-mae:8513.29222
[19]	validation_0-mae:8400.80048
[20]	validation_0-mae:8249.21686
[21]	validation_0-mae:8153.96229
[22]	validation_0-mae:8030.07208
[23]	validation_0-mae:7910.17169
[24]	validation_0-mae:7812.04354
[25]	validation_0-mae:7738.01708
[26]	validation_0-mae:7627.25738
[27]	validation_0-mae:7551.30255
[28]	validation_0-mae:7463.35277
[29]	validation_0-mae:7378.48515
[30]	valid

Best trial: 23. Best value: 3037.06:   16%|█▌        | 00:48/05:00

[0]	validation_0-mae:12658.81198
[1]	validation_0-mae:12206.88153
[2]	validation_0-mae:11776.01555
[3]	validation_0-mae:11424.73335
[4]	validation_0-mae:11063.52798
[5]	validation_0-mae:10764.41850
[6]	validation_0-mae:10457.37053
[7]	validation_0-mae:10198.30502
[8]	validation_0-mae:9956.13168
[9]	validation_0-mae:9713.16724
[10]	validation_0-mae:9526.02332
[11]	validation_0-mae:9317.84039
[12]	validation_0-mae:9044.00270
[13]	validation_0-mae:8859.49064
[14]	validation_0-mae:8614.62301
[15]	validation_0-mae:8437.65160
[16]	validation_0-mae:8225.51641
[17]	validation_0-mae:8061.41550
[18]	validation_0-mae:7871.05109
[19]	validation_0-mae:7731.85033
[20]	validation_0-mae:7593.83758
[21]	validation_0-mae:7423.38597
[22]	validation_0-mae:7270.26296
[23]	validation_0-mae:7156.60669
[24]	validation_0-mae:7011.66619
[25]	validation_0-mae:6898.71882
[26]	validation_0-mae:6777.36655
[27]	validation_0-mae:6645.96617
[28]	validation_0-mae:6522.19023
[29]	validation_0-mae:6444.75915
[30]	validat

Best trial: 25. Best value: 2558.19:   18%|█▊        | 00:54/05:00

[0]	validation_0-mae:12958.91128


Best trial: 25. Best value: 2558.19:   18%|█▊        | 00:55/05:00

[0]	validation_0-mae:12699.01394
[1]	validation_0-mae:12284.34332
[2]	validation_0-mae:11886.97363
[3]	validation_0-mae:11528.91429
[4]	validation_0-mae:11237.17997
[5]	validation_0-mae:10913.48289
[6]	validation_0-mae:10646.45613
[7]	validation_0-mae:10409.76756
[8]	validation_0-mae:10166.28446
[9]	validation_0-mae:9940.24117
[10]	validation_0-mae:9722.15864
[11]	validation_0-mae:9536.88359
[12]	validation_0-mae:9324.05075
[13]	validation_0-mae:9074.61098
[14]	validation_0-mae:8907.90690
[15]	validation_0-mae:8658.49344
[16]	validation_0-mae:8510.52863
[17]	validation_0-mae:8302.11065
[18]	validation_0-mae:8168.91272
[19]	validation_0-mae:8036.42891
[20]	validation_0-mae:7865.53135
[21]	validation_0-mae:7731.22865
[22]	validation_0-mae:7593.36289
[23]	validation_0-mae:7444.78037
[24]	validation_0-mae:7334.99838
[25]	validation_0-mae:7209.24852
[26]	validation_0-mae:7100.09974
[27]	validation_0-mae:6964.52968
[28]	validation_0-mae:6846.51860
[29]	validation_0-mae:6741.65047
[30]	valida

Best trial: 28. Best value: 2537.68:   20%|██        | 01:02/05:00

[0]	validation_0-mae:12882.62014


Best trial: 28. Best value: 2537.68:   21%|██        | 01:03/05:00

[0]	validation_0-mae:12633.95600
[1]	validation_0-mae:12157.33717
[2]	validation_0-mae:11729.05324
[3]	validation_0-mae:11364.27070
[4]	validation_0-mae:10995.50294
[5]	validation_0-mae:10687.88621
[6]	validation_0-mae:10386.84442
[7]	validation_0-mae:10124.94797
[8]	validation_0-mae:9848.61908
[9]	validation_0-mae:9605.70512
[10]	validation_0-mae:9356.60143
[11]	validation_0-mae:9182.39336
[12]	validation_0-mae:8926.00568
[13]	validation_0-mae:8723.75124
[14]	validation_0-mae:8555.95362
[15]	validation_0-mae:8309.69992
[16]	validation_0-mae:8161.14675
[17]	validation_0-mae:7949.14738
[18]	validation_0-mae:7803.11865
[19]	validation_0-mae:7638.19560
[20]	validation_0-mae:7473.71087
[21]	validation_0-mae:7348.86026
[22]	validation_0-mae:7219.32803
[23]	validation_0-mae:7045.53221
[24]	validation_0-mae:6897.41354
[25]	validation_0-mae:6785.39679
[26]	validation_0-mae:6675.87767
[27]	validation_0-mae:6528.64115
[28]	validation_0-mae:6413.14834
[29]	validation_0-mae:6312.66740
[30]	validat

Best trial: 28. Best value: 2537.68:   23%|██▎       | 01:09/05:00

[0]	validation_0-mae:12663.78615
[1]	validation_0-mae:12221.72873
[2]	validation_0-mae:11799.69556
[3]	validation_0-mae:11476.47792
[4]	validation_0-mae:11119.30065
[5]	validation_0-mae:10836.22065
[6]	validation_0-mae:10534.94460
[7]	validation_0-mae:10270.87919
[8]	validation_0-mae:9992.89759
[9]	validation_0-mae:9750.57515
[10]	validation_0-mae:9536.31888
[11]	validation_0-mae:9333.56579
[12]	validation_0-mae:9048.36191
[13]	validation_0-mae:8878.16107
[14]	validation_0-mae:8662.03999
[15]	validation_0-mae:8495.29530
[16]	validation_0-mae:8290.31418
[17]	validation_0-mae:8128.38708
[18]	validation_0-mae:7976.17006
[19]	validation_0-mae:7785.28177
[20]	validation_0-mae:7631.21545
[21]	validation_0-mae:7482.00610
[22]	validation_0-mae:7317.67821
[23]	validation_0-mae:7207.34535
[24]	validation_0-mae:7091.03090
[25]	validation_0-mae:6950.35977
[26]	validation_0-mae:6820.76784
[27]	validation_0-mae:6700.03480
[28]	validation_0-mae:6601.07372
[29]	validation_0-mae:6482.07533
[30]	validat

Best trial: 32. Best value: 2507.07:   25%|██▌       | 01:17/05:00

[0]	validation_0-mae:12654.65213
[1]	validation_0-mae:12205.56137
[2]	validation_0-mae:11777.95125
[3]	validation_0-mae:11443.10818
[4]	validation_0-mae:11082.06973
[5]	validation_0-mae:10794.94749
[6]	validation_0-mae:10491.88808
[7]	validation_0-mae:10229.15051
[8]	validation_0-mae:9955.77727
[9]	validation_0-mae:9694.79411
[10]	validation_0-mae:9448.35036
[11]	validation_0-mae:9233.41898
[12]	validation_0-mae:9045.54295
[13]	validation_0-mae:8799.21603
[14]	validation_0-mae:8578.66707
[15]	validation_0-mae:8411.38868
[16]	validation_0-mae:8228.50015
[17]	validation_0-mae:8032.21862
[18]	validation_0-mae:7877.93830
[19]	validation_0-mae:7681.10871
[20]	validation_0-mae:7543.12442
[21]	validation_0-mae:7390.86467
[22]	validation_0-mae:7222.24397
[23]	validation_0-mae:7093.35787
[24]	validation_0-mae:6999.45969
[25]	validation_0-mae:6878.00567
[26]	validation_0-mae:6741.36037
[27]	validation_0-mae:6617.53718
[28]	validation_0-mae:6518.85576
[29]	validation_0-mae:6416.03372
[30]	validat

Best trial: 32. Best value: 2507.07:   27%|██▋       | 01:23/05:00

[0]	validation_0-mae:12639.55712
[1]	validation_0-mae:12169.45890
[2]	validation_0-mae:11734.69654
[3]	validation_0-mae:11337.59898
[4]	validation_0-mae:11011.42254
[5]	validation_0-mae:10678.21666
[6]	validation_0-mae:10414.78683
[7]	validation_0-mae:10132.48698
[8]	validation_0-mae:9901.61343
[9]	validation_0-mae:9670.64487
[10]	validation_0-mae:9450.39125
[11]	validation_0-mae:9262.19120
[12]	validation_0-mae:9075.93893
[13]	validation_0-mae:8892.37794
[14]	validation_0-mae:8705.89638
[15]	validation_0-mae:8540.63088
[16]	validation_0-mae:8336.86469
[17]	validation_0-mae:8205.42732
[18]	validation_0-mae:8032.27221
[19]	validation_0-mae:7879.46414
[20]	validation_0-mae:7754.81345
[21]	validation_0-mae:7684.12274
[22]	validation_0-mae:7568.70259
[23]	validation_0-mae:7453.63052
[24]	validation_0-mae:7364.16260
[25]	validation_0-mae:7273.75535
[26]	validation_0-mae:7201.87441
[27]	validation_0-mae:7129.90016
[28]	validation_0-mae:7040.80757
[29]	validation_0-mae:6966.17837
[30]	validat

Best trial: 32. Best value: 2507.07:   30%|██▉       | 01:29/05:00

[0]	validation_0-mae:12981.21640


Best trial: 32. Best value: 2507.07:   30%|███       | 01:32/05:00

[0]	validation_0-mae:12661.08032
[1]	validation_0-mae:12217.76225
[2]	validation_0-mae:11803.30784
[3]	validation_0-mae:11467.30103
[4]	validation_0-mae:11123.11343
[5]	validation_0-mae:10858.08324
[6]	validation_0-mae:10579.93227
[7]	validation_0-mae:10334.04747
[8]	validation_0-mae:10096.25017
[9]	validation_0-mae:9879.94812
[10]	validation_0-mae:9662.70018
[11]	validation_0-mae:9458.60950
[12]	validation_0-mae:9291.27662
[13]	validation_0-mae:9091.11794
[14]	validation_0-mae:8849.76838
[15]	validation_0-mae:8680.62492
[16]	validation_0-mae:8477.12257
[17]	validation_0-mae:8336.86165
[18]	validation_0-mae:8182.45068
[19]	validation_0-mae:8036.77392
[20]	validation_0-mae:7921.95543
[21]	validation_0-mae:7797.97075
[22]	validation_0-mae:7676.52383
[23]	validation_0-mae:7560.13301
[24]	validation_0-mae:7469.17747
[25]	validation_0-mae:7386.13287
[26]	validation_0-mae:7313.23769
[27]	validation_0-mae:7226.55130
[28]	validation_0-mae:7153.39278
[29]	validation_0-mae:7101.58402
[30]	valida

Best trial: 32. Best value: 2507.07:   32%|███▏      | 01:36/05:00

[0]	validation_0-mae:12649.13499
[1]	validation_0-mae:12187.50710
[2]	validation_0-mae:11759.64053
[3]	validation_0-mae:11359.26461
[4]	validation_0-mae:10992.27620
[5]	validation_0-mae:10641.06176
[6]	validation_0-mae:10345.46749
[7]	validation_0-mae:10061.26789
[8]	validation_0-mae:9795.03970
[9]	validation_0-mae:9566.48895
[10]	validation_0-mae:9315.13744
[11]	validation_0-mae:9101.24497
[12]	validation_0-mae:8909.46877
[13]	validation_0-mae:8718.08698
[14]	validation_0-mae:8555.79576
[15]	validation_0-mae:8387.11510
[16]	validation_0-mae:8175.57746
[17]	validation_0-mae:7986.87802
[18]	validation_0-mae:7882.36942
[19]	validation_0-mae:7710.87556
[20]	validation_0-mae:7560.98701
[21]	validation_0-mae:7454.62476
[22]	validation_0-mae:7316.99796
[23]	validation_0-mae:7247.88101
[24]	validation_0-mae:7150.97778
[25]	validation_0-mae:7045.01392
[26]	validation_0-mae:6946.57801
[27]	validation_0-mae:6868.63811
[28]	validation_0-mae:6784.60912
[29]	validation_0-mae:6698.37051
[30]	validat

Best trial: 32. Best value: 2507.07:   34%|███▍      | 01:44/05:00

[0]	validation_0-mae:12694.99693
[1]	validation_0-mae:12242.31237
[2]	validation_0-mae:11855.62268
[3]	validation_0-mae:11539.96164
[4]	validation_0-mae:11259.25441
[5]	validation_0-mae:10992.53943
[6]	validation_0-mae:10779.01233
[7]	validation_0-mae:10586.05190


Best trial: 32. Best value: 2507.07:   35%|███▌      | 01:47/05:00

[0]	validation_0-mae:12546.04402
[1]	validation_0-mae:12009.87458
[2]	validation_0-mae:11507.93804
[3]	validation_0-mae:11104.88317
[4]	validation_0-mae:10673.63077
[5]	validation_0-mae:10342.41664
[6]	validation_0-mae:10001.23722
[7]	validation_0-mae:9696.75854
[8]	validation_0-mae:9397.88941
[9]	validation_0-mae:9128.84324
[10]	validation_0-mae:8878.86987
[11]	validation_0-mae:8667.18242
[12]	validation_0-mae:8358.38522
[13]	validation_0-mae:8186.10357
[14]	validation_0-mae:7930.64453
[15]	validation_0-mae:7703.09761
[16]	validation_0-mae:7531.56489
[17]	validation_0-mae:7315.92080
[18]	validation_0-mae:7125.82345
[19]	validation_0-mae:6962.47915
[20]	validation_0-mae:6774.47856
[21]	validation_0-mae:6636.62045
[22]	validation_0-mae:6498.36448
[23]	validation_0-mae:6335.40086
[24]	validation_0-mae:6198.30076
[25]	validation_0-mae:6084.65522
[26]	validation_0-mae:5944.07139
[27]	validation_0-mae:5810.98678
[28]	validation_0-mae:5683.43984
[29]	validation_0-mae:5578.41847
[30]	validati

Best trial: 47. Best value: 2346.75:   37%|███▋      | 01:53/05:00

[0]	validation_0-mae:12599.35388
[1]	validation_0-mae:12069.28114
[2]	validation_0-mae:11608.75590
[3]	validation_0-mae:11217.26064
[4]	validation_0-mae:10881.03617
[5]	validation_0-mae:10584.31224
[6]	validation_0-mae:10319.20368
[7]	validation_0-mae:10099.85106
[8]	validation_0-mae:9904.59331
[9]	validation_0-mae:9731.93654
[10]	validation_0-mae:9581.84247
[11]	validation_0-mae:9447.82753
[12]	validation_0-mae:9333.14278
[13]	validation_0-mae:9236.52224
[14]	validation_0-mae:9152.13663


Best trial: 47. Best value: 2346.75:   38%|███▊      | 01:56/05:00

[0]	validation_0-mae:12588.99630
[1]	validation_0-mae:12065.30173
[2]	validation_0-mae:11638.76243
[3]	validation_0-mae:11269.71560
[4]	validation_0-mae:10865.89390
[5]	validation_0-mae:10562.41866
[6]	validation_0-mae:10292.01801
[7]	validation_0-mae:10048.22370
[8]	validation_0-mae:9716.78781
[9]	validation_0-mae:9479.65048
[10]	validation_0-mae:9199.49355
[11]	validation_0-mae:9003.57819
[12]	validation_0-mae:8822.23988
[13]	validation_0-mae:8640.02873
[14]	validation_0-mae:8412.01549
[15]	validation_0-mae:8231.14132
[16]	validation_0-mae:8071.70403
[17]	validation_0-mae:7907.73827
[18]	validation_0-mae:7774.81768
[19]	validation_0-mae:7644.95571
[20]	validation_0-mae:7494.88680
[21]	validation_0-mae:7368.50722
[22]	validation_0-mae:7218.64337
[23]	validation_0-mae:7085.13263
[24]	validation_0-mae:6979.17160
[25]	validation_0-mae:6855.31054
[26]	validation_0-mae:6743.09698
[27]	validation_0-mae:6664.51164
[28]	validation_0-mae:6553.94763
[29]	validation_0-mae:6441.72631
[30]	validat

Best trial: 47. Best value: 2346.75:   40%|████      | 02:01/05:00

[0]	validation_0-mae:12731.65674


Best trial: 47. Best value: 2346.75:   41%|████▏     | 02:05/05:00

[0]	validation_0-mae:12689.72356
[1]	validation_0-mae:12242.61501
[2]	validation_0-mae:11862.32154
[3]	validation_0-mae:11520.15956
[4]	validation_0-mae:11228.04195
[5]	validation_0-mae:10949.17177
[6]	validation_0-mae:10664.85494
[7]	validation_0-mae:10447.16222
[8]	validation_0-mae:10203.52773
[9]	validation_0-mae:9938.43058
[10]	validation_0-mae:9734.89813
[11]	validation_0-mae:9561.09188
[12]	validation_0-mae:9355.16934
[13]	validation_0-mae:9170.05932
[14]	validation_0-mae:8963.22108
[15]	validation_0-mae:8796.36143
[16]	validation_0-mae:8662.19446
[17]	validation_0-mae:8499.72520
[18]	validation_0-mae:8362.47528
[19]	validation_0-mae:8224.93818
[20]	validation_0-mae:8088.26882
[21]	validation_0-mae:7943.88409
[22]	validation_0-mae:7829.37952
[23]	validation_0-mae:7715.05791
[24]	validation_0-mae:7598.12700
[25]	validation_0-mae:7463.69197
[26]	validation_0-mae:7358.42266
[27]	validation_0-mae:7223.07208
[28]	validation_0-mae:7123.36408
[29]	validation_0-mae:7036.62529
[30]	valida

Best trial: 47. Best value: 2346.75:   42%|████▏     | 02:08/05:00

[0]	validation_0-mae:12907.41110


Best trial: 47. Best value: 2346.75:   43%|████▎     | 02:11/05:00

[0]	validation_0-mae:12677.91923
[1]	validation_0-mae:12221.57605
[2]	validation_0-mae:11834.39280
[3]	validation_0-mae:11487.30729
[4]	validation_0-mae:11201.80702
[5]	validation_0-mae:10917.36627
[6]	validation_0-mae:10631.29535
[7]	validation_0-mae:10424.68261
[8]	validation_0-mae:10203.13809
[9]	validation_0-mae:9914.74137
[10]	validation_0-mae:9727.27989
[11]	validation_0-mae:9539.07201
[12]	validation_0-mae:9374.80174
[13]	validation_0-mae:9148.37094
[14]	validation_0-mae:9003.73986
[15]	validation_0-mae:8813.20458
[16]	validation_0-mae:8662.88547
[17]	validation_0-mae:8521.67707
[18]	validation_0-mae:8399.69325
[19]	validation_0-mae:8253.21893
[20]	validation_0-mae:8158.02242
[21]	validation_0-mae:8045.88766
[22]	validation_0-mae:7932.66817
[23]	validation_0-mae:7823.47248
[24]	validation_0-mae:7733.59788
[25]	validation_0-mae:7646.84226
[26]	validation_0-mae:7575.66299
[27]	validation_0-mae:7504.27339
[28]	validation_0-mae:7425.52387
[29]	validation_0-mae:7354.04520
[30]	valida

Best trial: 47. Best value: 2346.75:   44%|████▍     | 02:14/05:00

[0]	validation_0-mae:12712.43724


Best trial: 47. Best value: 2346.75:   45%|████▌     | 02:17/05:00

[0]	validation_0-mae:12611.79181
[1]	validation_0-mae:12111.63793
[2]	validation_0-mae:11691.62107
[3]	validation_0-mae:11331.79113
[4]	validation_0-mae:11039.66993
[5]	validation_0-mae:10702.27447
[6]	validation_0-mae:10432.23149
[7]	validation_0-mae:10176.33898
[8]	validation_0-mae:9924.96958
[9]	validation_0-mae:9732.16808
[10]	validation_0-mae:9448.46953
[11]	validation_0-mae:9266.91453
[12]	validation_0-mae:9029.34143
[13]	validation_0-mae:8857.79140
[14]	validation_0-mae:8702.41315
[15]	validation_0-mae:8548.07962
[16]	validation_0-mae:8413.99706
[17]	validation_0-mae:8265.21753
[18]	validation_0-mae:8139.72110
[19]	validation_0-mae:8023.56920
[20]	validation_0-mae:7915.03258
[21]	validation_0-mae:7800.21860
[22]	validation_0-mae:7681.57625
[23]	validation_0-mae:7587.90535
[24]	validation_0-mae:7490.66058
[25]	validation_0-mae:7423.67039
[26]	validation_0-mae:7344.07947
[27]	validation_0-mae:7287.03978
[28]	validation_0-mae:7231.83390
[29]	validation_0-mae:7176.62989
[30]	validat

Best trial: 47. Best value: 2346.75:   46%|████▌     | 02:19/05:00

[0]	validation_0-mae:12490.83028
[1]	validation_0-mae:11901.09363
[2]	validation_0-mae:11400.76407
[3]	validation_0-mae:10992.16148
[4]	validation_0-mae:10552.47554
[5]	validation_0-mae:10210.05942
[6]	validation_0-mae:9870.31763
[7]	validation_0-mae:9551.04564
[8]	validation_0-mae:9262.26107
[9]	validation_0-mae:9005.80119
[10]	validation_0-mae:8645.25375
[11]	validation_0-mae:8430.77858
[12]	validation_0-mae:8167.35426
[13]	validation_0-mae:7965.36036
[14]	validation_0-mae:7731.18454
[15]	validation_0-mae:7551.71779
[16]	validation_0-mae:7346.37661
[17]	validation_0-mae:7188.98552
[18]	validation_0-mae:6983.47378
[19]	validation_0-mae:6828.67795
[20]	validation_0-mae:6653.78610
[21]	validation_0-mae:6506.79835
[22]	validation_0-mae:6334.86517
[23]	validation_0-mae:6189.00323
[24]	validation_0-mae:6067.55245
[25]	validation_0-mae:5939.63466
[26]	validation_0-mae:5842.82079
[27]	validation_0-mae:5722.59583
[28]	validation_0-mae:5608.05121
[29]	validation_0-mae:5506.68625
[30]	validatio

Best trial: 47. Best value: 2346.75:   48%|████▊     | 02:27/05:00

[0]	validation_0-mae:12650.54132
[1]	validation_0-mae:12194.30604
[2]	validation_0-mae:11762.00498
[3]	validation_0-mae:11411.07262
[4]	validation_0-mae:11047.75689
[5]	validation_0-mae:10771.30845
[6]	validation_0-mae:10466.50494
[7]	validation_0-mae:10190.59124
[8]	validation_0-mae:9938.71284
[9]	validation_0-mae:9693.12102
[10]	validation_0-mae:9497.44580
[11]	validation_0-mae:9304.62542
[12]	validation_0-mae:9045.37405
[13]	validation_0-mae:8844.68437
[14]	validation_0-mae:8604.84570
[15]	validation_0-mae:8419.87629
[16]	validation_0-mae:8192.02372
[17]	validation_0-mae:8054.99358
[18]	validation_0-mae:7866.62253
[19]	validation_0-mae:7728.55905
[20]	validation_0-mae:7563.48806
[21]	validation_0-mae:7414.63790
[22]	validation_0-mae:7284.70556
[23]	validation_0-mae:7148.66234
[24]	validation_0-mae:7023.82688
[25]	validation_0-mae:6872.49961
[26]	validation_0-mae:6739.46852
[27]	validation_0-mae:6630.49888
[28]	validation_0-mae:6540.42412
[29]	validation_0-mae:6414.95027
[30]	validat

Best trial: 47. Best value: 2346.75:   51%|█████     | 02:33/05:00

[0]	validation_0-mae:12856.61579


Best trial: 47. Best value: 2346.75:   51%|█████▏    | 02:35/05:00

[0]	validation_0-mae:12577.35251
[1]	validation_0-mae:12062.95032
[2]	validation_0-mae:11613.11925
[3]	validation_0-mae:11242.50755
[4]	validation_0-mae:10851.58776
[5]	validation_0-mae:10565.16780
[6]	validation_0-mae:10303.48847
[7]	validation_0-mae:10021.63117
[8]	validation_0-mae:9775.88722
[9]	validation_0-mae:9519.23572
[10]	validation_0-mae:9294.44921
[11]	validation_0-mae:9072.67549
[12]	validation_0-mae:8861.73760
[13]	validation_0-mae:8614.78191
[14]	validation_0-mae:8443.02582
[15]	validation_0-mae:8230.14878
[16]	validation_0-mae:8097.87384
[17]	validation_0-mae:7933.40650
[18]	validation_0-mae:7782.38280
[19]	validation_0-mae:7663.26197
[20]	validation_0-mae:7522.89327
[21]	validation_0-mae:7426.06554
[22]	validation_0-mae:7322.26984
[23]	validation_0-mae:7252.63852
[24]	validation_0-mae:7175.52030
[25]	validation_0-mae:7082.27464
[26]	validation_0-mae:7006.57464
[27]	validation_0-mae:6940.23261
[28]	validation_0-mae:6859.37471
[29]	validation_0-mae:6802.89852
[30]	validat

Best trial: 47. Best value: 2346.75:   52%|█████▏    | 02:39/05:00

[0]	validation_0-mae:12648.52155
[1]	validation_0-mae:12190.06168
[2]	validation_0-mae:11758.47516
[3]	validation_0-mae:11352.72820
[4]	validation_0-mae:11028.92962
[5]	validation_0-mae:10675.81339
[6]	validation_0-mae:10393.00520
[7]	validation_0-mae:10118.13931
[8]	validation_0-mae:9834.63192
[9]	validation_0-mae:9587.48921
[10]	validation_0-mae:9358.62487
[11]	validation_0-mae:9121.92807
[12]	validation_0-mae:8910.93813
[13]	validation_0-mae:8734.96255
[14]	validation_0-mae:8486.99650
[15]	validation_0-mae:8247.63770
[16]	validation_0-mae:8097.61022
[17]	validation_0-mae:7931.70179
[18]	validation_0-mae:7720.05282
[19]	validation_0-mae:7575.84462
[20]	validation_0-mae:7413.82455
[21]	validation_0-mae:7250.05733
[22]	validation_0-mae:7068.63048
[23]	validation_0-mae:6933.99408
[24]	validation_0-mae:6761.62059
[25]	validation_0-mae:6638.45241
[26]	validation_0-mae:6483.88625
[27]	validation_0-mae:6349.95388
[28]	validation_0-mae:6254.56323
[29]	validation_0-mae:6150.39546
[30]	validat

Best trial: 67. Best value: 2344.76:   55%|█████▍    | 02:45/05:00

[0]	validation_0-mae:12394.46683
[1]	validation_0-mae:11729.73741
[2]	validation_0-mae:11131.28249
[3]	validation_0-mae:10621.91645
[4]	validation_0-mae:10110.08603
[5]	validation_0-mae:9647.84045
[6]	validation_0-mae:9254.85515
[7]	validation_0-mae:8882.89117
[8]	validation_0-mae:8538.14647
[9]	validation_0-mae:8270.10151
[10]	validation_0-mae:7897.54453
[11]	validation_0-mae:7556.17640
[12]	validation_0-mae:7203.18861
[13]	validation_0-mae:6977.80533
[14]	validation_0-mae:6781.46366
[15]	validation_0-mae:6522.57995
[16]	validation_0-mae:6252.15337
[17]	validation_0-mae:6051.94961
[18]	validation_0-mae:5825.90487
[19]	validation_0-mae:5651.86869
[20]	validation_0-mae:5493.48487
[21]	validation_0-mae:5301.10291
[22]	validation_0-mae:5134.59860
[23]	validation_0-mae:4984.88281
[24]	validation_0-mae:4879.29587
[25]	validation_0-mae:4766.66381
[26]	validation_0-mae:4631.76462
[27]	validation_0-mae:4518.03854
[28]	validation_0-mae:4427.76205
[29]	validation_0-mae:4319.84164
[30]	validation

Best trial: 68. Best value: 2133.47:   57%|█████▋    | 02:53/05:00

[0]	validation_0-mae:12410.44672
[1]	validation_0-mae:11755.59226
[2]	validation_0-mae:11175.41546
[3]	validation_0-mae:10673.54451
[4]	validation_0-mae:10182.95502
[5]	validation_0-mae:9743.32558
[6]	validation_0-mae:9346.81835
[7]	validation_0-mae:8974.05550
[8]	validation_0-mae:8650.88342
[9]	validation_0-mae:8233.67288
[10]	validation_0-mae:8010.37996
[11]	validation_0-mae:7666.92463
[12]	validation_0-mae:7346.50981
[13]	validation_0-mae:7105.76322
[14]	validation_0-mae:6813.84846
[15]	validation_0-mae:6631.74741
[16]	validation_0-mae:6369.39585
[17]	validation_0-mae:6132.22226
[18]	validation_0-mae:5942.57672
[19]	validation_0-mae:5737.93910
[20]	validation_0-mae:5579.09011
[21]	validation_0-mae:5398.89639
[22]	validation_0-mae:5233.22813
[23]	validation_0-mae:5106.14537
[24]	validation_0-mae:4972.31922
[25]	validation_0-mae:4840.82803
[26]	validation_0-mae:4711.37602
[27]	validation_0-mae:4581.48479
[28]	validation_0-mae:4469.10486
[29]	validation_0-mae:4380.23078
[30]	validation

Best trial: 68. Best value: 2133.47:   59%|█████▉    | 02:59/05:00

[0]	validation_0-mae:12393.80991
[1]	validation_0-mae:11727.31991
[2]	validation_0-mae:11138.03704
[3]	validation_0-mae:10631.86830
[4]	validation_0-mae:10134.63766
[5]	validation_0-mae:9674.96969
[6]	validation_0-mae:9265.41860
[7]	validation_0-mae:8878.81987
[8]	validation_0-mae:8549.70456
[9]	validation_0-mae:8262.44075
[10]	validation_0-mae:7891.31209
[11]	validation_0-mae:7523.90332
[12]	validation_0-mae:7218.03549
[13]	validation_0-mae:6994.54231
[14]	validation_0-mae:6737.59580
[15]	validation_0-mae:6457.99134
[16]	validation_0-mae:6282.28273
[17]	validation_0-mae:6085.69583
[18]	validation_0-mae:5852.87528
[19]	validation_0-mae:5688.99742
[20]	validation_0-mae:5480.52803
[21]	validation_0-mae:5314.96861
[22]	validation_0-mae:5174.55888
[23]	validation_0-mae:5014.39148
[24]	validation_0-mae:4872.19664
[25]	validation_0-mae:4770.47215
[26]	validation_0-mae:4681.27516
[27]	validation_0-mae:4555.98747
[28]	validation_0-mae:4479.69356
[29]	validation_0-mae:4374.67673
[30]	validation

Best trial: 68. Best value: 2133.47:   61%|██████▏   | 03:06/05:00

[0]	validation_0-mae:12382.57713
[1]	validation_0-mae:11707.04918
[2]	validation_0-mae:11110.96894
[3]	validation_0-mae:10599.93582
[4]	validation_0-mae:10105.75601
[5]	validation_0-mae:9640.83057
[6]	validation_0-mae:9226.23320
[7]	validation_0-mae:8852.58650
[8]	validation_0-mae:8510.76172
[9]	validation_0-mae:8110.48179
[10]	validation_0-mae:7847.11148
[11]	validation_0-mae:7485.98698
[12]	validation_0-mae:7212.79652
[13]	validation_0-mae:6896.39060
[14]	validation_0-mae:6690.41407
[15]	validation_0-mae:6442.67751
[16]	validation_0-mae:6189.39026
[17]	validation_0-mae:5998.90207
[18]	validation_0-mae:5765.81615
[19]	validation_0-mae:5590.22993
[20]	validation_0-mae:5393.84432
[21]	validation_0-mae:5216.55726
[22]	validation_0-mae:5077.18425
[23]	validation_0-mae:4944.55030
[24]	validation_0-mae:4795.21600
[25]	validation_0-mae:4689.18789
[26]	validation_0-mae:4571.90827
[27]	validation_0-mae:4456.32885
[28]	validation_0-mae:4379.26151
[29]	validation_0-mae:4284.89213
[30]	validation

Best trial: 71. Best value: 2117.53:   64%|██████▎   | 03:13/05:00

[0]	validation_0-mae:12423.98959
[1]	validation_0-mae:11780.63429
[2]	validation_0-mae:11200.64876
[3]	validation_0-mae:10705.71687
[4]	validation_0-mae:10220.96861
[5]	validation_0-mae:9789.01942
[6]	validation_0-mae:9384.94939
[7]	validation_0-mae:9017.08408
[8]	validation_0-mae:8698.79450
[9]	validation_0-mae:8295.88290
[10]	validation_0-mae:8033.11062
[11]	validation_0-mae:7659.33102
[12]	validation_0-mae:7436.97196
[13]	validation_0-mae:7133.03932
[14]	validation_0-mae:6841.13340
[15]	validation_0-mae:6662.28083
[16]	validation_0-mae:6429.32452
[17]	validation_0-mae:6191.55043
[18]	validation_0-mae:6012.69484
[19]	validation_0-mae:5791.17101
[20]	validation_0-mae:5619.70955
[21]	validation_0-mae:5432.20555
[22]	validation_0-mae:5250.69251
[23]	validation_0-mae:5112.60377
[24]	validation_0-mae:4966.60099
[25]	validation_0-mae:4869.72220
[26]	validation_0-mae:4733.88312
[27]	validation_0-mae:4615.82127
[28]	validation_0-mae:4521.13749
[29]	validation_0-mae:4416.26082
[30]	validation

Best trial: 72. Best value: 2114.65:   66%|██████▌   | 03:21/05:00

[0]	validation_0-mae:12382.46801
[1]	validation_0-mae:11707.88276
[2]	validation_0-mae:11112.50205
[3]	validation_0-mae:10602.23104
[4]	validation_0-mae:10107.23808
[5]	validation_0-mae:9642.53470
[6]	validation_0-mae:9219.27601
[7]	validation_0-mae:8852.83399
[8]	validation_0-mae:8524.58815
[9]	validation_0-mae:8242.56201
[10]	validation_0-mae:7854.36734
[11]	validation_0-mae:7471.22727
[12]	validation_0-mae:7136.93787
[13]	validation_0-mae:6927.70016
[14]	validation_0-mae:6656.26587
[15]	validation_0-mae:6376.37972
[16]	validation_0-mae:6126.94671
[17]	validation_0-mae:5887.32932
[18]	validation_0-mae:5744.75148
[19]	validation_0-mae:5587.79673
[20]	validation_0-mae:5401.47291
[21]	validation_0-mae:5211.54755
[22]	validation_0-mae:5068.39421
[23]	validation_0-mae:4944.82794
[24]	validation_0-mae:4814.17688
[25]	validation_0-mae:4706.15669
[26]	validation_0-mae:4570.93964
[27]	validation_0-mae:4455.19185
[28]	validation_0-mae:4368.53233
[29]	validation_0-mae:4278.79448
[30]	validation

Best trial: 72. Best value: 2114.65:   69%|██████▉   | 03:28/05:00

[0]	validation_0-mae:12383.94754
[1]	validation_0-mae:11712.24035
[2]	validation_0-mae:11107.18483
[3]	validation_0-mae:10593.57896
[4]	validation_0-mae:10078.48184
[5]	validation_0-mae:9614.77522
[6]	validation_0-mae:9221.79391
[7]	validation_0-mae:8879.00517
[8]	validation_0-mae:8518.66777
[9]	validation_0-mae:8220.54795
[10]	validation_0-mae:7832.97694
[11]	validation_0-mae:7479.82701
[12]	validation_0-mae:7238.70615
[13]	validation_0-mae:6927.88397
[14]	validation_0-mae:6701.94178
[15]	validation_0-mae:6435.55298
[16]	validation_0-mae:6181.84499
[17]	validation_0-mae:6039.79208
[18]	validation_0-mae:5860.56886
[19]	validation_0-mae:5629.05141
[20]	validation_0-mae:5455.14749
[21]	validation_0-mae:5290.50925
[22]	validation_0-mae:5143.75985
[23]	validation_0-mae:4968.67078
[24]	validation_0-mae:4832.53609
[25]	validation_0-mae:4731.68903
[26]	validation_0-mae:4602.15084
[27]	validation_0-mae:4491.24681
[28]	validation_0-mae:4393.25445
[29]	validation_0-mae:4323.52770
[30]	validation

Best trial: 72. Best value: 2114.65:   71%|███████▏  | 03:36/05:00

[0]	validation_0-mae:12542.69366
[1]	validation_0-mae:11972.67352
[2]	validation_0-mae:11487.59442
[3]	validation_0-mae:11072.23263
[4]	validation_0-mae:10716.65502
[5]	validation_0-mae:10405.71788
[6]	validation_0-mae:10147.60165
[7]	validation_0-mae:9920.81133
[8]	validation_0-mae:9723.07374
[9]	validation_0-mae:9554.43274
[10]	validation_0-mae:9407.29502


Best trial: 72. Best value: 2114.65:   72%|███████▏  | 03:39/05:00

[0]	validation_0-mae:12454.73688
[1]	validation_0-mae:11786.96623
[2]	validation_0-mae:11202.98193
[3]	validation_0-mae:10738.22633
[4]	validation_0-mae:10318.31615
[5]	validation_0-mae:9949.09916
[6]	validation_0-mae:9603.57105
[7]	validation_0-mae:9312.88043
[8]	validation_0-mae:9041.38013
[9]	validation_0-mae:8777.13687
[10]	validation_0-mae:8561.24472
[11]	validation_0-mae:8389.08271
[12]	validation_0-mae:8204.30992
[13]	validation_0-mae:8011.79770
[14]	validation_0-mae:7855.54645
[15]	validation_0-mae:7705.14275
[16]	validation_0-mae:7536.40986
[17]	validation_0-mae:7410.52043
[18]	validation_0-mae:7286.24188
[19]	validation_0-mae:7190.23625
[20]	validation_0-mae:7081.94518
[21]	validation_0-mae:7004.45554
[22]	validation_0-mae:6916.18994
[23]	validation_0-mae:6816.67583
[24]	validation_0-mae:6732.46706
[25]	validation_0-mae:6624.86043
[26]	validation_0-mae:6547.86511
[27]	validation_0-mae:6456.13423
[28]	validation_0-mae:6334.77867
[29]	validation_0-mae:6280.72886
[30]	validation

Best trial: 72. Best value: 2114.65:   73%|███████▎  | 03:42/05:00

[0]	validation_0-mae:12458.42296
[1]	validation_0-mae:11834.70670
[2]	validation_0-mae:11281.01999
[3]	validation_0-mae:10772.11714
[4]	validation_0-mae:10309.67854
[5]	validation_0-mae:9876.54431
[6]	validation_0-mae:9480.82869
[7]	validation_0-mae:9102.36044
[8]	validation_0-mae:8773.15828
[9]	validation_0-mae:8494.66230
[10]	validation_0-mae:8210.87383
[11]	validation_0-mae:7942.64414
[12]	validation_0-mae:7610.61645
[13]	validation_0-mae:7298.79657
[14]	validation_0-mae:7024.07282
[15]	validation_0-mae:6749.45574
[16]	validation_0-mae:6577.41996
[17]	validation_0-mae:6379.74024
[18]	validation_0-mae:6201.63593
[19]	validation_0-mae:5976.65936
[20]	validation_0-mae:5784.65984
[21]	validation_0-mae:5595.61001
[22]	validation_0-mae:5434.88403
[23]	validation_0-mae:5279.81920
[24]	validation_0-mae:5144.19671
[25]	validation_0-mae:5034.99615
[26]	validation_0-mae:4928.59834
[27]	validation_0-mae:4826.03939
[28]	validation_0-mae:4699.51122
[29]	validation_0-mae:4597.31518
[30]	validation

Best trial: 72. Best value: 2114.65:   76%|███████▌  | 03:49/05:00

[0]	validation_0-mae:12470.99941
[1]	validation_0-mae:11860.21167
[2]	validation_0-mae:11310.55249
[3]	validation_0-mae:10822.21216
[4]	validation_0-mae:10388.66139
[5]	validation_0-mae:10007.73579
[6]	validation_0-mae:9681.34864
[7]	validation_0-mae:9362.10825
[8]	validation_0-mae:9075.83311
[9]	validation_0-mae:8799.64834
[10]	validation_0-mae:8537.40588
[11]	validation_0-mae:8347.87063
[12]	validation_0-mae:8071.23701
[13]	validation_0-mae:7818.87192
[14]	validation_0-mae:7607.08169
[15]	validation_0-mae:7454.60492
[16]	validation_0-mae:7344.08589
[17]	validation_0-mae:7168.98052
[18]	validation_0-mae:7048.30333
[19]	validation_0-mae:6904.71639
[20]	validation_0-mae:6805.86776
[21]	validation_0-mae:6693.68722
[22]	validation_0-mae:6606.69154
[23]	validation_0-mae:6510.15557
[24]	validation_0-mae:6432.31042
[25]	validation_0-mae:6335.35761
[26]	validation_0-mae:6264.80863
[27]	validation_0-mae:6157.17789
[28]	validation_0-mae:6086.59171
[29]	validation_0-mae:5981.60945
[30]	validatio

Best trial: 72. Best value: 2114.65:   78%|███████▊  | 03:55/05:00

[0]	validation_0-mae:12399.92621
[1]	validation_0-mae:11749.29709
[2]	validation_0-mae:11163.40585
[3]	validation_0-mae:10665.14514
[4]	validation_0-mae:10216.73416
[5]	validation_0-mae:9798.41577
[6]	validation_0-mae:9459.45759
[7]	validation_0-mae:9124.02371
[8]	validation_0-mae:8822.31836
[9]	validation_0-mae:8573.94059
[10]	validation_0-mae:8310.97839
[11]	validation_0-mae:8008.20979
[12]	validation_0-mae:7737.08701
[13]	validation_0-mae:7511.53177
[14]	validation_0-mae:7387.08333
[15]	validation_0-mae:7186.96130
[16]	validation_0-mae:7030.63899
[17]	validation_0-mae:6886.33729
[18]	validation_0-mae:6811.97232
[19]	validation_0-mae:6701.42315
[20]	validation_0-mae:6574.68953
[21]	validation_0-mae:6497.14269
[22]	validation_0-mae:6396.16486
[23]	validation_0-mae:6308.64026
[24]	validation_0-mae:6215.90160
[25]	validation_0-mae:6109.05477
[26]	validation_0-mae:6039.95445
[27]	validation_0-mae:5952.40057
[28]	validation_0-mae:5855.91437
[29]	validation_0-mae:5784.91941
[30]	validation

Best trial: 72. Best value: 2114.65:   79%|███████▉  | 03:59/05:00

[0]	validation_0-mae:12613.69920
[1]	validation_0-mae:12115.85725
[2]	validation_0-mae:11665.27757
[3]	validation_0-mae:11238.90638
[4]	validation_0-mae:10864.43071
[5]	validation_0-mae:10482.02109
[6]	validation_0-mae:10177.53526
[7]	validation_0-mae:9869.48011
[8]	validation_0-mae:9548.62618
[9]	validation_0-mae:9267.55897
[10]	validation_0-mae:8994.87283
[11]	validation_0-mae:8757.93752
[12]	validation_0-mae:8525.79745
[13]	validation_0-mae:8288.73758
[14]	validation_0-mae:8007.03141
[15]	validation_0-mae:7736.85698
[16]	validation_0-mae:7491.14583
[17]	validation_0-mae:7318.10459
[18]	validation_0-mae:7077.74927
[19]	validation_0-mae:6864.27409
[20]	validation_0-mae:6693.59594
[21]	validation_0-mae:6505.70341
[22]	validation_0-mae:6400.30805
[23]	validation_0-mae:6249.88829
[24]	validation_0-mae:6073.57070
[25]	validation_0-mae:5927.57781
[26]	validation_0-mae:5775.28501
[27]	validation_0-mae:5647.68279
[28]	validation_0-mae:5523.08876
[29]	validation_0-mae:5384.63526
[30]	validati

Best trial: 81. Best value: 2083.24:   81%|████████  | 04:06/05:00

[0]	validation_0-mae:12486.54331
[1]	validation_0-mae:11887.43299
[2]	validation_0-mae:11372.95499
[3]	validation_0-mae:10880.80894
[4]	validation_0-mae:10447.94435
[5]	validation_0-mae:10016.07609
[6]	validation_0-mae:9632.15954
[7]	validation_0-mae:9254.16403
[8]	validation_0-mae:8940.70561
[9]	validation_0-mae:8645.84328
[10]	validation_0-mae:8413.68523
[11]	validation_0-mae:8073.21080
[12]	validation_0-mae:7824.19337
[13]	validation_0-mae:7528.81967
[14]	validation_0-mae:7296.68603
[15]	validation_0-mae:7015.66152
[16]	validation_0-mae:6760.96061
[17]	validation_0-mae:6592.35658
[18]	validation_0-mae:6373.86265
[19]	validation_0-mae:6223.89375
[20]	validation_0-mae:6010.69315
[21]	validation_0-mae:5853.85719
[22]	validation_0-mae:5678.94559
[23]	validation_0-mae:5534.83906
[24]	validation_0-mae:5411.72053
[25]	validation_0-mae:5241.56068
[26]	validation_0-mae:5109.61193
[27]	validation_0-mae:5016.50101
[28]	validation_0-mae:4884.57863
[29]	validation_0-mae:4759.01257
[30]	validatio

Best trial: 82. Best value: 2069.89:   83%|████████▎ | 04:12/05:00

[0]	validation_0-mae:12543.43339
[1]	validation_0-mae:11990.99342
[2]	validation_0-mae:11487.51048
[3]	validation_0-mae:11014.70498
[4]	validation_0-mae:10604.04648
[5]	validation_0-mae:10204.34406
[6]	validation_0-mae:9846.65421
[7]	validation_0-mae:9517.93979
[8]	validation_0-mae:9210.03567
[9]	validation_0-mae:8912.90144
[10]	validation_0-mae:8639.01615
[11]	validation_0-mae:8427.76950
[12]	validation_0-mae:8115.46377
[13]	validation_0-mae:7884.66008
[14]	validation_0-mae:7608.23613
[15]	validation_0-mae:7337.19808
[16]	validation_0-mae:7147.51731
[17]	validation_0-mae:6896.09631
[18]	validation_0-mae:6737.51203
[19]	validation_0-mae:6546.75898
[20]	validation_0-mae:6347.12432
[21]	validation_0-mae:6169.76512
[22]	validation_0-mae:6033.59009
[23]	validation_0-mae:5849.06282
[24]	validation_0-mae:5722.72584
[25]	validation_0-mae:5562.68410
[26]	validation_0-mae:5440.92783
[27]	validation_0-mae:5302.30312
[28]	validation_0-mae:5177.31841
[29]	validation_0-mae:5067.91536
[30]	validatio

Best trial: 82. Best value: 2069.89:   85%|████████▌ | 04:19/05:00

[0]	validation_0-mae:12558.33051
[1]	validation_0-mae:12017.82423
[2]	validation_0-mae:11532.27620
[3]	validation_0-mae:11071.10864
[4]	validation_0-mae:10662.35130
[5]	validation_0-mae:10265.62040
[6]	validation_0-mae:9916.54266
[7]	validation_0-mae:9589.83431
[8]	validation_0-mae:9308.58674
[9]	validation_0-mae:9015.35546
[10]	validation_0-mae:8747.04749
[11]	validation_0-mae:8501.84150
[12]	validation_0-mae:8191.94049
[13]	validation_0-mae:7952.95807
[14]	validation_0-mae:7687.17689
[15]	validation_0-mae:7434.26557
[16]	validation_0-mae:7252.41323
[17]	validation_0-mae:7003.86550
[18]	validation_0-mae:6854.29693
[19]	validation_0-mae:6656.18639
[20]	validation_0-mae:6428.05514
[21]	validation_0-mae:6278.49355
[22]	validation_0-mae:6090.10665
[23]	validation_0-mae:5959.05052
[24]	validation_0-mae:5778.28308
[25]	validation_0-mae:5614.52345
[26]	validation_0-mae:5500.42914
[27]	validation_0-mae:5359.47766
[28]	validation_0-mae:5246.31371
[29]	validation_0-mae:5130.25924
[30]	validatio

Best trial: 82. Best value: 2069.89:   88%|████████▊ | 04:26/05:00

[0]	validation_0-mae:12675.27127


Best trial: 82. Best value: 2069.89:   90%|████████▉ | 04:32/05:00

[0]	validation_0-mae:12584.22673
[1]	validation_0-mae:12042.33213
[2]	validation_0-mae:11577.29983
[3]	validation_0-mae:11179.80532
[4]	validation_0-mae:10833.75067
[5]	validation_0-mae:10530.01534


Best trial: 82. Best value: 2069.89:   92%|█████████▏| 04:39/05:00

[0]	validation_0-mae:12553.55539
[1]	validation_0-mae:12010.98821
[2]	validation_0-mae:11514.83560
[3]	validation_0-mae:11069.87347
[4]	validation_0-mae:10661.05919
[5]	validation_0-mae:10300.08042
[6]	validation_0-mae:9960.20143
[7]	validation_0-mae:9676.64922
[8]	validation_0-mae:9370.67005
[9]	validation_0-mae:9119.28706
[10]	validation_0-mae:8867.89098
[11]	validation_0-mae:8653.69082
[12]	validation_0-mae:8479.62774
[13]	validation_0-mae:8216.12240
[14]	validation_0-mae:7983.68641
[15]	validation_0-mae:7825.71450
[16]	validation_0-mae:7632.53371
[17]	validation_0-mae:7461.73784
[18]	validation_0-mae:7370.76079
[19]	validation_0-mae:7236.32819
[20]	validation_0-mae:7094.59554


Best trial: 82. Best value: 2069.89:   93%|█████████▎| 04:43/05:00

[0]	validation_0-mae:12626.21437


Best trial: 82. Best value: 2069.89:   95%|█████████▍| 04:46/05:00

[0]	validation_0-mae:12462.20589
[1]	validation_0-mae:11838.28640
[2]	validation_0-mae:11292.55305
[3]	validation_0-mae:10778.62545
[4]	validation_0-mae:10321.23010
[5]	validation_0-mae:9891.69781
[6]	validation_0-mae:9500.48526
[7]	validation_0-mae:9130.20315
[8]	validation_0-mae:8805.72818
[9]	validation_0-mae:8516.81221
[10]	validation_0-mae:8221.76278
[11]	validation_0-mae:7946.48831
[12]	validation_0-mae:7617.33211
[13]	validation_0-mae:7306.56772
[14]	validation_0-mae:7022.40888
[15]	validation_0-mae:6842.86093
[16]	validation_0-mae:6587.82930
[17]	validation_0-mae:6402.62923
[18]	validation_0-mae:6168.26478
[19]	validation_0-mae:5965.81685
[20]	validation_0-mae:5815.53568
[21]	validation_0-mae:5628.49296
[22]	validation_0-mae:5477.38880
[23]	validation_0-mae:5348.96716
[24]	validation_0-mae:5219.26462
[25]	validation_0-mae:5099.96465
[26]	validation_0-mae:4952.80471
[27]	validation_0-mae:4831.95683
[28]	validation_0-mae:4737.37037
[29]	validation_0-mae:4622.28281
[30]	validation

Best trial: 82. Best value: 2069.89:   97%|█████████▋| 04:54/05:00

[0]	validation_0-mae:12462.53234
[1]	validation_0-mae:11847.04510
[2]	validation_0-mae:11291.89173
[3]	validation_0-mae:10799.88605
[4]	validation_0-mae:10364.32408
[5]	validation_0-mae:9981.77107
[6]	validation_0-mae:9656.05564
[7]	validation_0-mae:9340.45429
[8]	validation_0-mae:9056.03236
[9]	validation_0-mae:8768.31487
[10]	validation_0-mae:8513.14142
[11]	validation_0-mae:8329.18223
[12]	validation_0-mae:8063.60423
[13]	validation_0-mae:7810.82998
[14]	validation_0-mae:7587.02251
[15]	validation_0-mae:7446.32141
[16]	validation_0-mae:7257.74752
[17]	validation_0-mae:7169.88239
[18]	validation_0-mae:7036.63993
[19]	validation_0-mae:6923.51876
[20]	validation_0-mae:6796.72630


Best trial: 82. Best value: 2069.89:   98%|█████████▊| 04:58/05:00

[0]	validation_0-mae:12522.46411
[1]	validation_0-mae:11949.80012
[2]	validation_0-mae:11436.15147
[3]	validation_0-mae:10953.34929
[4]	validation_0-mae:10532.45201
[5]	validation_0-mae:10124.75498
[6]	validation_0-mae:9750.87253
[7]	validation_0-mae:9389.18062
[8]	validation_0-mae:9079.33506
[9]	validation_0-mae:8774.06709
[10]	validation_0-mae:8524.14417
[11]	validation_0-mae:8186.89935
[12]	validation_0-mae:7858.94600
[13]	validation_0-mae:7636.02443
[14]	validation_0-mae:7359.76735
[15]	validation_0-mae:7157.72442
[16]	validation_0-mae:6911.03258
[17]	validation_0-mae:6691.62824
[18]	validation_0-mae:6471.07393
[19]	validation_0-mae:6334.96288
[20]	validation_0-mae:6181.21112
[21]	validation_0-mae:5967.63592
[22]	validation_0-mae:5827.98313
[23]	validation_0-mae:5650.37593
[24]	validation_0-mae:5503.60678
[25]	validation_0-mae:5359.87538
[26]	validation_0-mae:5258.41811
[27]	validation_0-mae:5146.40260
[28]	validation_0-mae:5019.89633
[29]	validation_0-mae:4920.19590
[30]	validatio

Best trial: 82. Best value: 2069.89:  100%|██████████| 05:05/05:00


Trials ejecutados: 94
Mejor MAE validación: 2069.89
Mejores hiperparámetros:
  learning_rate: 0.085617042833164
  n_estimators: 599
  max_depth: 7
  max_leaves: 85
  min_child_weight: 1
  reg_alpha: 0.5031204644318659
  reg_lambda: 0.8071465184114838
  ohe_min_frequency: 0.06263425902727707


['xgb_optuna_pruning.pkl']

Podemos ver que el mejor MAE empeoro ligeramente de 2008 a 2069, siendo que podríamos esperar que como se probaron más combinaciones debería ser mejor, esto puede deberse a que algunos se cortaron antes de llegar a su mejor valor.

## 5. Visualizaciones (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/F-LgB1xTebEAAAAd/look-at-this-graph-nickelback.gif">
</p>


Satisfecho con su trabajo, Fiu le pregunta si es posible generar visualizaciones que permitan entender el entrenamiento de su modelo.

A partir del siguiente <a href = https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html#visualization>enlace</a>, genere las siguientes visualizaciones:

1. Gráfico de historial de optimización [1 punto]
2. Gráfico de coordenadas paralelas [1 punto]
3. Gráfico de importancia de hiperparámetros [1 punto]

Comente sus resultados:

4. ¿Desde qué *trial* se empiezan a observar mejoras notables en sus resultados? [0.5 puntos]
5. ¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas? [1 punto]
6. ¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo? [0.5 puntos]

In [21]:
# Inserte su código acá
from optuna.visualization import (
    plot_optimization_history,
    plot_parallel_coordinate,
    plot_param_importances,
)

plot_optimization_history(study_prune).show()

plot_parallel_coordinate(study_prune).show()

plot_param_importances(study_prune).show()

4. Los primeros trials valen mucho más que los posteriores, más que desde que trial se empieza a notar mejoras notables, podemos ver que desde más o menos el trial número 10, las mejoras disminuyen muchísimo
5. en general los trials con valores bajos en mae tienen un learning rate cercano a 0.1, max_depth menor a 7, max_leaves mayor a 60, n_estimators mayor a 500, ohe_min_freq menor a 0.2, reg_alpha entre 0.2 y 0.6, y finalmente reg_lambda entre 0.6 y 0.8
6. por mucho son n_estimators y ohe_min_frequency

## 6. Síntesis de resultados (3 puntos)

Finalmente:

1. Genere una tabla resumen del MAE en el conjunto de validación obtenido en los 5 modelos entrenados desde Baseline hasta XGBoost con Constraints, Optuna y Prunning. [1 punto]
2. Compare los resultados de la tabla y responda, ¿qué modelo obtiene el mejor rendimiento? [0.5 puntos]
3. Cargue el mejor modelo, prediga sobre el conjunto de **test** y reporte su MAE. [0.5 puntos]
4. ¿Existen diferencias con respecto a las métricas obtenidas en el conjunto de validación? ¿Porqué puede ocurrir esto? [1 punto]

In [24]:
# Inserte su código acá
modelos = {
    "Baseline": joblib.load("baseline_dummy.pkl"),
    "XGBoost": joblib.load("xgb_default.pkl"),
    "XGBoost + Monotone": joblib.load("xgb_monotone_price_neg.pkl"),
    "XGBoost + Optuna": joblib.load("xgb_optuna.pkl"),
    "XGBoost + Optuna + Pruning": joblib.load("xgb_optuna_pruning.pkl"),
}

resultados = []
for nombre, modelo in modelos.items():
    y_pred = modelo.predict(X_val)
    mae = mean_absolute_error(y_val, y_pred)
    resultados.append({"Modelo": nombre, "MAE_Validación": mae})

tabla_mae = pd.DataFrame(resultados)
display(tabla_mae)

Modelo  MAE_Validación
0                    Baseline    13176.150888
1                     XGBoost     2545.905762
2          XGBoost + Monotone     2510.528076
3            XGBoost + Optuna     2008.553955
4  XGBoost + Optuna + Pruning     2069.894287

El mejor modelo es el de optuna sin pruning a nivel de tener el menor MAE

In [25]:
best_model = joblib.load("xgb_optuna.pkl")
y_pred_test = best_model.predict(X_test)
mae_test = mean_absolute_error(y_test, y_pred_test)
print(f"MAE en Test: {mae_test:.4f}")

MAE en Test: 2330.4026


Podemos ver que el MAE en Test es considerablemente pero que el de validación siendo de 2330 contra los 2008 de validación, esto ocurre porqe al momento de hacer una optimización de hiperparámetros estamos introduciendo un sesgo hacia los datos de validación de la misma forma que el modelo tiene un sesgo y se sobreajusta a los datos de entrenamiento, al momento de optimizar respecto a validación estamos sobreajustando hacia esos datos, por eso es tan importante probar solamente al final en los de test pues si intentamos ahora hacer algo para mejorar los resultados de test estamos introduciendo un sesgo hacia esos datos con respecto al universo real.

# Conclusión
Exito!
<p align="center">
  <img src="https://i.pinimg.com/originals/55/3d/42/553d42bea9b10e0662a05aa8726fc7f4.gif">
</p>