x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: airflow/Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    ML_PIPELINE_DATA_PATH: /opt/airflow/data
    ML_PIPELINE_MODELS_PATH: /opt/airflow/storage/models
    ML_PIPELINE_PREDICTIONS_PATH: /opt/airflow/storage/predictions
    ML_PIPELINE_CLIENTES_FILE: ${ML_PIPELINE_CLIENTES_FILE:-clientes.parquet}
    ML_PIPELINE_PRODUCTOS_FILE: ${ML_PIPELINE_PRODUCTOS_FILE:-productos.parquet}
    ML_PIPELINE_TRANSACCIONES_FILE: ${ML_PIPELINE_TRANSACCIONES_FILE:-transacciones.parquet}
    ML_PIPELINE_OPTUNA_N_TRIALS: ${ML_PIPELINE_OPTUNA_N_TRIALS:-20}
  volumes:
    - .:/opt/airflow
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --role Admin --username admin --password admin --firstname admin --lastname admin --email admin@example.com"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
